### ISSUE TITLE
Use quotes that indicate no interpolation required.

### ISSUE THREAD

**Issue by RalphCorderoy** [mvdan/sh#100]
Novice sh programmers often don't grasp that everything's a string and so `42` is no different to `'42'`. Due to their familiarity with other languages, they'll use `""` in preference to `''` because _that's how strings are meant to look_. But if no interpolation of the quoted text is required, it's quicker for the reader to see `''` because they can then skip the string content when skimming whereas `""` means they have to grok the string too.

Replace `""` with `''` where it makes no difference to the evaluation, e.g.

    date +"%Y-%m-%d %T %z %a"
    date +'%Y-%m-%d %T %z %a'

That will also clean up the excess escaping required due to the wrong quote being used.

    printf "%s\\t%s\\n" "\$HOME" "$HOME"
    printf '%s\t%s\n' '$HOME' "$HOME"

**Comment by mvdan** [comment]
When you say "reader", do you mean the lexer here or the human eye? If you mean the former, keep in mind the difference is not significant. The lexer still looks at every byte to keep track of line numbers, for example.

Are you suggesting that `shfmt` do this? Note that I considered a "simplify" flag in https://github.com/mvdan/sh/issues/34, but decided against it - see my last comment there. For the same reason that I think replacing `${foo}` -> `$foo` could break style or consistency with code around it, I think `"foo"` -> `'foo'` would not be generally useful.

Open to ideas, but just not convinced this would be useful.

**Comment by RalphCorderoy** [comment]
I meant the human reader; surely the most important. ;-)

**Comment by mvdan** [comment]
I have to admit I prefer `"` for consistency with other strings in a program and because I'm used to `'` being for runes/chars. I only use `'` for what you would call "string literals", as in strings I'm using for regexes or sed, or strings that otherwise are probably going to contain special characters.

What you're suggesting here and in the other issue, is it a new flag like what I proposed in the older issue? Have you had a chance to read my conclusion there? I still think enforcing these things would just annoy most developers.

**Comment by mvdan** [comment]
Bump @RalphCorderoy

**Comment by mvdan** [comment]
Closing in favor of the new `shfmt -s` issue.
