### ISSUE TITLE
go get from gopkg.in fails with undefined tokens

### ISSUE THREAD

**Issue by marccarre** [mvdan/sh#107]
First and foremost, thanks for developing & maintaining `shfmt`! It truly is a great tool!

However, it looks like something is incorrectly setup on [gopkg.in/mvdan/sh.v1/cmd/shfmt](http://gopkg.in/mvdan/sh.v1/cmd/shfmt) as `go get`-ting it recently started to fail with the below errors:

```
$ docker run -ti golang

### The below fails:
root@d11c54a20a60:/go# go get gopkg.in/mvdan/sh.v1/cmd/shfmt
# gopkg.in/mvdan/sh.v1/cmd/shfmt
src/gopkg.in/mvdan/sh.v1/cmd/shfmt/main.go:26: undefined: "github.com/mvdan/sh/syntax".ParseMode
src/gopkg.in/mvdan/sh.v1/cmd/shfmt/main.go:27: undefined: "github.com/mvdan/sh/syntax".PrintConfig
src/gopkg.in/mvdan/sh.v1/cmd/shfmt/main.go:46: undefined: "github.com/mvdan/sh/syntax".ParseComments
src/gopkg.in/mvdan/sh.v1/cmd/shfmt/main.go:48: undefined: "github.com/mvdan/sh/syntax".PosixConformant
src/gopkg.in/mvdan/sh.v1/cmd/shfmt/main.go:73: undefined: "github.com/mvdan/sh/syntax".Parse
src/gopkg.in/mvdan/sh.v1/cmd/shfmt/main.go:139: undefined: "github.com/mvdan/sh/syntax".Parse

### Works as you'd expect but is a moving target:
root@d11c54a20a60:/go# go get github.com/mvdan/sh/cmd/shfmt
```

**Comment by marccarre** [comment]
Note that, as suggested [here](https://github.com/weaveworks/build-tools/pull/99#issuecomment-302365357), the following works around the issue & allows to use a fixed version:
```
$ docker run -ti golang
root@874cdb2295fc:/go# cd /go/src && \
>   mkdir -p github.com/mvdan && \
>   cd "$_" && \
>   git clone --branch v1.3.0 --single-branch https://github.com/mvdan/sh.git >/dev/null 2>&1 && \
>   cd sh/cmd/shfmt && \
>   go install && \
>   cd /go/src && \
>   rm -fr github.com
root@874cdb2295fc:/go/src# which shfmt
/go/bin/shfmt
```

This is, however, much more involved.

**Comment by mvdan** [comment]
Glad to hear the tool is useful :)

Unfortunately, this is not something I can fix on my end easily. The way `gopkg.in` seems to work is that when you import `gopkg.in/mvdan/sh.v1/cmd/shfmt`, it builds `github.com/mvdan/sh/cmd/shfmt` at v1. But `cmd/shfmt` imports `github.com/mvdan/syntax`, not `gopkg.in/mvdan/sh.v1/syntax`, so you're trying to build `cmd/shfmt` v1 with `syntax` v2. (v2 is not released yet, so it's master right now).

There are a few workarounds on your end:

* Build from source from v1.3.0 or whatever other specific version (or the `v1` branch) like you're doing now
* Download one of the binaries I publish in the releases page

On my end, I can't rewrite the import paths in `v1` to be tied to `gopkg.in`. That would mean that the only way to build `v1` would be by using `gopkg.in`, which I don't want to have to depend on on all cases.

I thought `gopkg.in` would realise that all of these packages come from the same repo and use `v1` for all of them, but I guess it's not that clever.

A possible workaround on my end would be to have `master` be `v1` instead of the latest version `v2`, which isn't released yet. But I'm not keen on doing that. For one, we would be in the same situation when `v3` comes around - whatever `master` points to, some `gopkg.in` build path would be broken.

And for another, I want `master` to be the latest version - that's why the version branches exist.

I hope that explains the whole situation. If you want to avoid the complexity of doing the checout via git, you can download a binary. If you want to build from source at all costs, I'm afraid there's little you can do with regards to simplifying it since `go get` doesn't handle that sort of stuff.

Perhaps a way to make it prettier would be to have a script that would `git clone` with a certain branch/tag and build that, so you could make the `shfmt` thing a one-liner calling the script.

**Comment by mvdan** [comment]
Also, in your script, the lines

```
	cd sh/cmd/shfmt && \
	go install && \
```

could be simplified to

```
	go install ./sh/cmd/shfmt && \
```

**Comment by mvdan** [comment]
I see that while I was writing this, you've opted for downloading a binary in your PRs. I'm going to close this for now.

If you think there's a solution on my end that will not make the project depend on `gopkg.in` nor mess up the branches, I'll be happy to try it out.

**Comment by marccarre** [comment]
Thanks for the quick reply & detailed explanation @mvdan! 
It indeed looks more like a `gopkg.in` issue... or more fundamentally, a Go package management issue but heh... `¯\_(ツ)_/¯`.

I'm personally fine with either workaround, so all good for now.
