### ISSUE TITLE
interp: Support "sh" buildin

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#115]
Currently, calling another bash script with `sh file.sh` fallback to native OS' `sh`. On Windows, it will not work. I think it makes sense to run the file with the own interpreter.

Thought: maybe also for `bash`?

**Comment by mvdan** [comment]
This is sticky. What if the user really meant the system's shell?

I think this could be opt-in. By default, no commands would point to the interpreter itself. Then you could specify which ones you want to add, like `sh`, `bash` et al.

Note that `.` and `source` are different because they run the program in the current shell, instead of spawning a new one.

**Comment by andreynering** [comment]
> Note that `.` and `source` are different because they run the program in the current shell, instead of spawning a new one.

Hmm... you're right, `.` is more appropriated for calling another file.

So, not necessary to add the `sh` buildin. But I'll keep this issue open in case you decide to implement it as optional in the future.

**Comment by mvdan** [comment]
I'd do the opposite - keep it closed for now. You should tell users to use `.` instead of `sh`.

If that turns out to be impossible for some reason or some scenario, we can look into making the interpreter more complex. But for now, I see no need.
