### ISSUE TITLE
parse: fails at tests.sh in github.com/reconquest/tests.sh

### ISSUE THREAD

**Issue by seletskiy** [mvdan/sh#12]
First issue is that `:` is not allowed in the function names, however, it's valid (at least in bash 4+).

Second issue:

```
tests.sh:164:14: reached < without matching token ${ with }
```

**Comment by mvdan** [comment]
specWorks now :) Thanks for reporting!spec

**Comment by seletskiy** [comment]
@mvdan: Are you sure about removing spaces after `<` and `<<<`.

In my opinion, `cat <<< "$blah"` looks nicer, than `cat <<<"$blah"`

**Comment by mvdan** [comment]
There should not be spaces after redirect tokens, i.e. `foo bar <a >b <<EOF`. This is very common and helps readability, since it might be otherwise hard to distinguish redirects from regular arguments or other nodes like pipes. It is also the style that the POSIX Shell spec uses.

I'm not sure that we should treat `<<<` any differently than the rest. This page does use a space:

http://www.tldp.org/LDP/abs/html/x17837.html

But their own tests use both versions.

**Comment by seletskiy** [comment]
@mvdan: Don't see, how lack of whitespaces will improve readability. It works in opposite direction: it's easier for brain to distinguish elements when they are separated by whitespaces. Also, it's very difficult to misinterpret `<` or `<<<` as regular arguments, because they need to be quoted/escaped to be regular araguments: `\<`, `'<'`.

**Comment by seletskiy** [comment]
Also, process substitution uses whitespace after `>` or `<`: `> >(blah)`.

**Comment by mvdan** [comment]
Take this: `foo a > b c < d e <<< f g`

It is much easier to see which are arguments and which are redirection words if we do not use spaces:

`foo a >b c <d e <<<f g`

Besides, this is the POSIX Shell spec format, and the most widely used format. I don't see why we should go against those two.

> Also, process substitution uses whitespace after > or <: > >(blah).

This is a requirement, as otherwise `>>(foo)` would become an append on `(foo)`.

**Comment by seletskiy** [comment]
@mvdan: Your example is invalid (two input redirections), and anyway should be rewritten to form where arguments come first:  
`foo a c e g > b < d` or to
`foo a c e g > b <<< f`

**Comment by mvdan** [comment]
Might be invalid to execute, but it's a valid to parse :)

And yeah, you have a point regarding arguments coming first. `shfmt` even enforces that.

I'm really undecided as to what to do. On one hand no spaces is what the spec uses and what is used out there, but on the other hand spaces make everything consistent with process substitution.

I'd like more input before making a decision. CC @ebfe @mattn or anyone else welcome to chime in.

**Comment by mattn** [comment]
About meaning for motivation of developing this, as your said, some people want to use shfmt to format shell scripts. And some people want to get AST from shell scripts (for example, detect dangerous script or something). Currently, As far as I can see, the people want to use shfmt seems greater than the second one.

**Comment by mvdan** [comment]
@mattn I was asking whether people prefer `foo > bar` or `foo >bar`, having in mind the ups and downs of each.

**Comment by ebfe** [comment]
FWIW, I actually prefer the no-space variant, but have no real argument for it except "That's what I use, and commonly see used".

**Comment by mattn** [comment]
Ah, one of answers from me. I prefer put space.

**Comment by mvdan** [comment]
So right now `shfmt` allows a number of redirects before any command arguments, to allow things such as:

```sh
echo >&2 "foo bar"
```

I suggest the format become:

```
foo >a >&2 bar > a < b >&2 <<< "c" <<< EOF
EOF
```

As in, always space redirects except those before arguments or those with `>&` (since `&N` means a file descriptor, but we cannot do `> &N`).

Thoughts?

**Comment by ebfe** [comment]
> I suggest the format become:
> 
> ```
> foo >a >&2 bar > a < b >&2 <<< "c" <<< EOF
> EOF
> ```

I think that's a good example where not adding the space actually would
improve readability, because it's easier to see at a glance where
the redirects are.

**Comment by mvdan** [comment]
> I think that's a good example where not adding the space actually would improve readability, because it's easier to see at a glance where the redirects are.

I never use spaces because I too think they hurt readability. But some people disagree.

Thinking again about my proposal there, it's way too complicated compared to our current approach. And always adding spaces would mean confusing things such as:

```sh
foo > a >& 2 bar > a < b >& 2 <<< "c" <<< EOF
EOF
```

`&N` should never be split, and separating the first `>a` doesn't make much sense either.

**Comment by seletskiy** [comment]
@mvdan: I believe '>&2' should be `>& 2`, because it's semantically different operator (redirection to fiile descriptor).
