### ISSUE TITLE
cmd/shfmt: add -d for diff mode

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#122]
It would be great for `shfmt` to support diff mode similar to `gofmt -d`. The diffing will be handled by the `diff` utility of the host.

From conversations in #68 and #121

**Comment by jamesmstone** [comment]
A similar thing is done in [`dockfmt`](https://github.com/jessfraz/dockfmt/blob/master/format.go#L254-279)

**Comment by mvdan** [comment]
My only doubt is whether or not to depend on `diff`. Points in favor are consistency with `gofmt`, simplicity to implement and the fact that people can replace the binary to get different behaviors.

Points against are adding a dependency on a system tool to an otherwise fully static binary, and how using an external binary makes things slower and forces us to use temporary files. But I guess slowing things down is not a big problem if we have to calculate diffs anyway.

Anyone willing to work on a patch for this?

**Comment by jamesmstone** [comment]
Would be happy to give it a crack, however I wouldn't be able to make a start for about a month. *sigh* exams *sigh*. 
So if anyone else wants to grab it, by all means

**Comment by mvdan** [comment]
2.0 is already packed with new stuff, so I actually think it's a good idea to not get to this now. I plan on doing that release in the next couple of weeks. We can include this in a later 2.1 or 2.2.

**Comment by mvdan** [comment]
Friendly ping @jamesmstone - now that 2.0 is released, feel free to work on this and send a patch whenever. Otherwise, I'll get to it sometime in a few weeks.

**Comment by jamesmstone** [comment]
Cheers, so the plan is to use systems `diff`?

**Comment by mvdan** [comment]
Yeah, just look at `gofmt`'s code that handles this. We can look at native Go diff libs later, but for now let's go with the safe option.

**Comment by mvdan** [comment]
@jamesmstone would you still like to work on this? I'm pushing this back to 2.2 for now, in case you still do.

**Comment by mmlb** [comment]
🎉 thanks @mvdan. :( that I dropped implementing this :(
