### ISSUE TITLE
syntax: undo "$ literal must be escaped" restriction

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#130]
Somewhere between 1.3.1 and master shfmt started to error on lines like:

```
$ cat y.sh
sed -e "s/^int$/ssize_t/" 
$ shfmt y.sh 
y.sh:1:15: $ literal must be escaped or single-quoted

$ cat x.sh
echo $/
$ shfmt x.sh
x.sh:1:6: $ literal must be escaped or single-quoted
```

bash (4.4.1) seems to be fine without escaping:
```
$ echo $/
$/
```

**Comment by mvdan** [comment]
This is on purpose. See https://github.com/mvdan/sh/commit/aff61d46da2808fc650d7c5bade1ef7671f6c5b9 for details.

Not only does this make the parser simpler, it also forces you to write saner shell - it forces you to avoid the ambiguity of `$`. Unless escaped or in single quotes, it must always start an expansion.

This is similar to how the parser always assumes `$((` starts an arithmetic expression, without handling the ambiguity with `$( (`.

Do you think this was a bad decision? I personally think not.

**Comment by ebfe** [comment]
In the context of purely `shfmt` I can understand your argument, though i think
i'd still prefer it to be as relaxed as it can on the input side.

As a user of primarily `sh/syntax` to parse shells scripts i have no intention of
formatting, the change is indeed a bit annoying. `$/` comes up relatively
often in sed expressions.

**Comment by mvdan** [comment]
I think you're right. I applied this change to the parser thinking only of the formatter, not so much other uses like the interpreter.

The `$((` change is different because it concerns backtracking. This is just a bit of extra code to do a limited amount of look-ahead.

For now I'll revert the change and make the parser accept this again. At a later time, I might teach `shfmt` to escape dollar signs, perhaps as part of `-s`.

**Comment by mvdan** [comment]
By the way, what do you use the syntax package for? I know a couple of projects that use it along with the interpreter, but I've yet to find any non-trivial use of the syntax package alone (other than my own projects).

**Comment by ebfe** [comment]
Thanks! ATM i have mostly trivial uses for `syntax` as well. E.g. finding variable assignments (and the conditions they happen under) or command/function invocations in xbps templates. The ultimate goal is to have a syntax-aware replacement for our regexp based linter. That also is mostly finding variable assignments and verifying some properties on the assigned value.

**Comment by mvdan** [comment]
Thanks for the info - let me know how it works out :)

If you'd like to build something generic, like a simpler version of the AST (similar to SSA) or some sort of static analysis or value range propagation, that might be useful to include here too.

**Comment by mvdan** [comment]
Another similar restriction I added - borrowed from `mksh` - is the parser erroring on unclosed heredocs, i.e. when they're closed by an actual end-of-file. I wonder if I should too undo that change in master.

In my defense, that is a warning - but not an error, apparently - in Bash.

**Comment by mvdan** [comment]
Ping @ebfe? I'm still undecided about this other breaking change that I did on master. Input would be appreciated.

**Comment by ebfe** [comment]
This one seems much less problematic to me. I suspect in most cases where this
actually does come up, it's really an accidental omission/typo/indention of
the end-marker or a truncated file. And in a lot of (most?) instances, that
would generate some kind of syntax error later anyway. So it might even be
helpfull in diagnosing where the real error is.

Sorry to be no real help here, but I'm undecided too ;)

**Comment by mvdan** [comment]
I'm decided again. I was undecided because I thought it could be useful in interactive shells. But in that case, you would just press enter, write the input and hit `^D`. There is no reason to do `<<EOF` before the enter, which would get you the warning on Bash.

The fact that the POSIX Shell spec makes no mention of heredocs that end with an end-of-file makes this a stronger case. And it also errors under some shells.

So won't be reverting that one. And thank god, because the code to handle the two cases was tricky.
