### ISSUE TITLE
report all variables used

### ISSUE THREAD

**Issue by brentp** [mvdan/sh#139]
this is not a bug.

I would like to send an `io.Reader` to something driven by `sh`  that will return all variables that are accessed by the script that are undefined.

It's not clear to me how to do this. Is this something that is relatively feasible?

So, e.g. given a bash script like:

```

beta=1235

echo $beta
echo $alpha

for i in *.txt; do
    echo $i $missing
done
```

it would return `[]string{"alpha", "missing"}` ?

thanks.

**Comment by mvdan** [comment]
This sounds similar to `set -u`. Have you looked into that?

This could also be done with some basic static analysis, but it wouldn't be exactly the same check - it wouldn't be at run-time.

**Comment by brentp** [comment]
yes, within the scripts, I use `set -u` but I want to know before run-time what variables will need to be defined.
a bit of context is that this is for jobs submitted to AWS batch. It can be expensive to have all the machinery spin up and EBS volumes attached only to hit an undefined error. I'd like to check for other errors too, but I thought that getting unset variables might be a good start.

thanks for the reply.

**Comment by mvdan** [comment]
The only way to know for sure is to actually run it, e.g. locally instead of on these servers. In that case, `set -u` is what you want.

On the other hand, if you don't want to have to run it, you could do some sort of static analysis as mentioned above. But as all static analysis tools, it could either be conservative or greedy - you would get false negatives or false positives.

For example, if a script runs an executable, there's no way to know what would its output be unless you actually run it.

So I'm not sure what you're asking for. This sounds like some sort of static analysis tool on top of the `syntax` package. At the moment, this project includes no static analysis tools. There could be with fairly little effort as everything else is built, but I've been lazy given how one already exists, with quite a lot of checks: https://github.com/koalaman/shellcheck

**Comment by brentp** [comment]
shellcheck looks great but I was looking for something in go so I could have it be a check before job submission. I'll go ahead and close this as out-of-scope for this library. thanks for your insight all the same.

**Comment by mvdan** [comment]
Note that I didn't mean to say this was out of scope. Just that I haven't considered static analysis as there is already an alternative and I'm lazy.

Also curious - how does Go make this easier for you? Besides writing the code, I mean.

**Comment by brentp** [comment]
I am using go library/command-line tool to submit jobs (bash scripts) to [AWS Batch](https://aws.amazon.com/batch/) 

before actually submitting the job, I'd like to have the library check for obvious problems with the submission.

if you have guidance on how to start, I'd be interested to look into this. On quick glance I didn't see even what type of `Node` I would be looking for.

**Comment by mvdan** [comment]
Ah right, you're running Go.

I'm on holidays at the moment so my laptop time is very limited. On the phone, the best advice I can give is to use Walk and see the tree of nodes you get.

In particular, you'd want Assign and ParamExp, for setting and getting vars.
