### ISSUE TITLE
Incorrect nested quote parsing in subshell

### ISSUE THREAD

**Issue by sublimino** [mvdan/sh#142]
Sorry for the weird bug report, ~~I promise it's valid BASH~~ it's not actually valid BASH (the declaration works, but executing the tab-completion generates an error), but it gives unexpected output  :fearful:

```
# cat > /tmp/test <<EOF 
complete -W '\$(awk -F'->' '{print \$1}')'
EOF

# cat /tmp/test 
complete -W '$(awk -F'->' '{print $1}')'
```
This produces unexpected output:
```
# shfmt /tmp/test
complete -W '$(awk -F'- $1}')' >' '{print
```

The problem appears to be the nested single quotes in the subshell. Changing the argument to `awk -F` to double quotes fixes it:

```
# cat > /tmp/test <<EOF 
complete -W '\$(awk -F"->" '{print \$1}')'
EOF

# shfmt /tmp/test
complete -W '$(awk -F"->" '{print $1}')'
```

Independent of indent level.

**Comment by mvdan** [comment]
In single quotes, `$(` are not special characters. As such, the second single quote isn't nested - it closes the first. The weird output comes from parsing the rest of the input like that - the `>` is parsed as a redirect.

It probably runs fine on bash because, just like in the case of our parser, it's a valid program. Just not the one you wanted or one that will succeed.

**Comment by sublimino** [comment]
Good point, thanks for reminding!
