### ISSUE TITLE
cmd/shfmt: change default indentation to 4 spaces to match bash8

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#151]
Could the default indentation be set to `-i 4`, to match the style recommended by [OpenStack](https://github.com/openstack-dev/bashate)?

**Comment by mvdan** [comment]
Is there a reason to? You can still use the flag, or use an alias or script if you'd like to avoid the extra typing.

There is no consensus on indentation for shell code in general. Google is two spaces, some others are tabs, this one and others are four spaces.

However, I went with tabs as the default because Bash slightly leans towards tab indentation. And that is because of `<<-`. In this style of heredoc, leading tabs are ignored in the heredoc body and the heredoc end line. This can make for much more readable heredocs - but it would mean mixing tabs and spaces if you were to indent with tabs.

Other than that, the choice of the default is as good as any other. So I see no great need to change it either. Do you feel like there is?

**Comment by mvdan** [comment]
I agree that two spaces and four spaces are reasonable defaults; so is tabs. My point here is that there is not one value that is canonical nor notoriously more popular than the others. This is the whole reason why there is an option instead of just forcing a value in the first place.

And, since this tool has been around with the current default for a while, I need good reason to break backwards compatibility in the command line tool.

I don't understand your point about the heredocs. I'm not saying you should use `<<-`. My point is that as a language feature, it treats tabs differently to allow for indented heredoc bodies. Quoting from `man bash`:

    If the redirection operator is <<-, then all leading tab characters are stripped from input lines and the line containing delimiter. This allows here-documents within shell scripts to be indented in a natural fashion.

The language favors tab indentation in this very specific case. It doesn't favor any other sort of indentaiton style anywhere else, which is why I mentioned that the Bash (not shell) language slightly leans towards tabs.

This is the reasoning that I originally used to tell myself that this was an objectively reasonable default, ignoring the multiple standards out there that dictate different styles.

Please do note that this is not a style war. The tool supports any indentation style you want. I chose a default that was best to my knowledge. There really isn't much else to it.

**Comment by mvdan** [comment]
A week has passed, and 2.0 is close, so I'm going to close this. We can revisit this and other defaults/flags for v3, but I still think the current default is fine.
