### ISSUE TITLE
Add ability to get syntax.ParamExp "value".

### ISSUE THREAD

**Issue by onodera-punpun** [mvdan/sh#165]
I don't know if this is the scope of `syntax`, or if it's somehow already possible, but I'm looking for the following:

I have a BASH file that looks like this:

```bash
name=firefox
version=52.4.0esr
release=1
source=(https://ftp.mozilla.org/pub/firefox/releases/$version/source/firefox-$version.source.tar.xz
	firefox-install-dir.patch firefox.desktop)
```

Now I want to get the value of `source`, so I'm doing this:

```go
for _, s := range t.Array.Elems {
	for _, sp := range s.Value.Parts {
		switch spt := sp.(type) {
		case *syntax.Lit:
			fmt.Print(spt.Value)
		case *syntax.ParamExp:
			fmt.Print(spt.Param.Value)
	}
}
fmt.Println()
```

Which prints the following:

```
https://ftp.mozilla.org/pub/firefox/releases/version/source/firefox-version.source.tar.xz
firefox-install-dir.patch
firefox.desktop
```

However I want it to print:

```
https://ftp.mozilla.org/pub/firefox/releases/52.4.0esr/source/firefox-52.4.0esr.source.tar.xz
firefox-install-dir.patch
firefox.desktop
```

However it doesn't seem possible to print the "value" of `spt.Param.Value`. I'm probably not using the correct terminology here, but I hope you get what I mean.

**Comment by mvdan** [comment]
Yes - you want to evaluate the expansions.

The simplest way to do this is already mostly working, which is interpreting a program: https://godoc.org/mvdan.cc/sh/interp

You could, for example, interpret your file there, and then interpret a single `echo $foo`, by either parsing that string first or constructing it yourself like `&syntax.CallExpr{Args: []Word{{Parts: []syntax.WordPart{&syntax.Lit{"echo"}}}}, ...}`.

This has the caveat that you're interpreting and running any program at all, so it could be dangerous or risky. You could work around this by first using `syntax.Walk` and ensuring that, for example, only assignments without any command substitutions take place.

I guess you could argue the need for a "static" analysis mode, which interpreted a mode in such a strict mode - only allowing for plain shell logic, assignments and a few builtins, skipping or erroring on anything else. I wonder if such a thing would be a good idea. Open to discussing it, as using shell files as configuration files (like Arch's PKGBUILDS and so on).

**Comment by mvdan** [comment]
Please note, however, that the godoc there is lacking, there are no examples and the API is rough around the edges. You might need to tinker with the internals a little bit to use the runner in the way you want, such as running an entire program first and then running some commands after.

**Comment by ebfe** [comment]
FWIW i've been working on something similar and ran into similar situations. That is: wanting to evaluate a single ParamExp (ArithmExpr, ...) given an existing environment, while making sure nothing is accidentally executed/touching disks/etc. Current solution is to reimplement the logic which is implemented by interp but not exposed directly.

**Comment by mvdan** [comment]
If the proposed `Expand` ignored command substitutions, so that `Expand("foo $(upload private-info) bar")` would error, would this be a good solution?

Note that it's secondary whether such a func would take a node or a string - going from one to another is fairly trivial.

One possible signature:

    func (r *Runner) Fields(words ...*Word) ([]string, error)

(returning `[]string` because you want `$foo` to expand to `[]string{"x", "y"}` if `foo="x y"`)

This is almost exactly in place already as `Runner.fields`, with the exception that it doesn't error on commands. I believe forbidding commands (i.e. statements in this package's lingo) should get rid of all possible side effects, including redirections.

**Comment by mvdan** [comment]
Working on a patch at the moment, will post a pull request soon asking for both of your comments and reviews :)

**Comment by ebfe** [comment]
On Thu, Oct 12, 2017 at 03:21:11PM +0000, Daniel Martí wrote:
> If the proposed `Expand` ignored command substitutions, so that
> `Expand("foo $(upload private-info) bar")` would error, would this be
> a good solution?

This wouldn't really work for my use-case (though i admit it might be a
bit on the esoteric side). I still want to allow/emulate some CmdSubsts
(e.g. invoking sh functions) . Maybe with something like
https://github.com/mvdan/sh/issues/147 in place it would be doable.

**Comment by mvdan** [comment]
I am actually thinking the same now. I was implementing the filter in the `syntax` package, but that way you'd forbid all builtins too, which would break simple stuff like `true`.

Perhaps we should make the pieces of code that open files (such as redirects) and execute programs (such as cmds that are neither builtins nor user-defined funcs), so that you may replace these with a func that just errors. I believe that would be powerful enough for what you want.

Then you'd do something like:

```
r := NewRunner()
r.Exec = func(...) ... { return ..., fmt.Errorf("cannot execute arbitrary programs") }
r.Open = func(...) ... { return ..., fmt.Errorf("cannot open arbitrary files") }
```

Of course, that way you'd be able to whitelist certain strings such as the `sed` program or the `/dev/null` file.

**Comment by onodera-punpun** [comment]
>Do you happen to have numbers or an example? It does take more time (~1.5x last I checked) than bash -n, but it is doing more work and it is constructing an AST, which is bound to hammer allocations.

I basically wanted to replace the stuff in [this function](https://github.com/onodera-punpun/prt/blob/library/ports/pkgfile.go#L54) with `interp` or `syntax`. Since even bash is too slow for my liking (for example when calculating the dependencies of a package recursively it will call bash a dozen of times which will result in a noticeable delay of output) I think I will just replace my use of `source` [here](https://github.com/onodera-punpun/prt/blob/library/ports/pkgfile.go#L96) with `interp` or `syntax`.

I think a function in interp that mimics the function I wrote [here](https://github.com/onodera-punpun/prt/blob/library/ports/pkgfile.go#L162) would be perfect for my usecase.

**Comment by mvdan** [comment]
Yeah, what you're after would be doable. Not sure if there would be a wrapper to do a single line, but definitely doable in a few lines.

**Comment by mvdan** [comment]
I have made some good progress today. @onodera-punpun working example for your use case: https://gist.github.com/mvdan/25fb3b01a05866db01884066339e6e88

Note that the func isn't small, since I added the building blocks for this via the modules instead of writing a helper func exactly for what you need. Adding such a helper func would still be possible, but I don't think that would be a good idea.

However, there are certainly parts that could be made simpler. For example, the `verbosity below is ${name[@]}` could be replaced with something like `p.Words("${"+name+"[@]}")`, provided that you knew the `name` input was safe.

And perhaps the two modules (for exec and open) could be built into the library, under "no side effects" names. However, I feel like that could mean different things depending on what the developer is after. So I'd rather keep it out for now.

If either of you can come up with a nicer API that could sit on top of all this, do let me know. Thanks!

**Comment by mvdan** [comment]
@onodera-punpun did you have a chance to try the snippet above?

**Comment by onodera-punpun** [comment]
Sorry I haven't been working on that project lately, I'll try it out this weekend!

**Comment by mvdan** [comment]
I'm going to close this in favor of #198. The proposed package should have a higher-level APIs that should let you do the basics without having to resort to the lower levels of  `syntax` and `interp`.

**Comment by mvdan** [comment]
@onodera-punpun I've now added `interp.SourceFile` and `interp.SourceNode` - please try those out. Now your use case should really be just three lines.
