### ISSUE TITLE
Detect misused variable names

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#166]
Some special variable names are provided by certain shells, but not others. For example, `$BASH_VERSION` is available in some bash interpreters. Could the mvdan/sh parser warn when special variable names are referenced from the wrong shell language?

**Comment by mvdan** [comment]
This is an interesting proposal, but it has no place in the parser. For example, what if a POSIX Shell script defines a bash variable and uses it later on? A static parser cannot tell a false positive apart.

This could be done in the interpreter, however. But I'm not sure how useful that would be. Perhaps the script is using a Bash var to tell if it's running under Bash or not.

In the last few suggestion issues that you have opened, I have followed up with questions and ideas that you didn't answer. I hope you'll answer this time. There's little point in keeping the issue open more than a few days otherwise.
