### ISSUE TITLE
interp: patterns are ignored in replace parameter expansions

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#177]
```sh
X=Afoo
echo ${X/foo} ${X/foo/B}
echo ${X/fo*} ${X/fo*/B}
```

bash
```
A AB
A AB
```

gosh
```
A AB
Afoo Afoo
```

**Comment by mvdan** [comment]
Ah, I forgot that patterns are used here too. They had only been added to the prefix/suffix removal so far.

**Comment by mvdan** [comment]
Eugh, this requires our own full-blown implementation of pattern matching. Until now we were abusing `path.Match`, which works with prefixes and suffixes in a bruteforce way, but can't be used here at all.

Will take me a bit to get this working, I presume.

**Comment by ebfe** [comment]
> Until now we were abusing path.Match

Ah, right. Then #179 is in the same category i guess.

**Comment by mvdan** [comment]
Yes. I'll need to add these extra features one by one.

**Comment by mvdan** [comment]
@ebfe actually, you might be able to help me decide if something is a good idea or not.

Writing this from the ground up would be very similar to re-implementing half of the `regexp` package in Go. A lot of things are extremely similar, such as `*`, `?`, character ranges, and character classes.

I'm wondering if, instead of implementing this from the ground up, we could translate these patterns into proper regexes. For example, `foo*bar[abc]` would become `foo[^/]*bar[abc]` (since slashes must always be matched explicitly).

It can obviously work for simple cases, but I'm trying to convince myself if this would be enough to cover all the stuff in http://wiki.bash-hackers.org/syntax/pattern, while still being fast and simple.

It would definitely be simpler than reimplementing a pattern/regexp matching engine, for sure.

**Comment by mvdan** [comment]
We would also need to escape characters that are special in a regex but not a bash pattern, such as `foo.bar` becoming `foo\.bar`.

**Comment by ebfe** [comment]
That's what python does for fnmatch, see
https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/fnmatch.py#L74

**Comment by mvdan** [comment]
Great - proof that it at least works elsewhere. I still haven't figured out a way it could backfire worse than us reimplementing from scratch.

Going this route, I should have all of this done in a few hours.

**Comment by mvdan** [comment]
This might bite us in the ass, though: http://wiki.bash-hackers.org/syntax/pattern#extended_pattern_language

Those extended features don't seem like enough reason to implement all of this from scratch, though. Worst comes to worst, we can simply not implement some of these extra bash features that barely anyone uses.
