### ISSUE TITLE
cmd/shfmt: Please document what standard, if any, shfmt enforces by default

### ISSUE THREAD

**Issue by notjames** [mvdan/sh#212]
We have started using shfmt and with that plus the call for standardizing on a specific standard (now google's bash guide), is using shfmt (strictly for style) conformant to any specific style? If so, which?

**Comment by mvdan** [comment]
This is a good idea - it's not very well documented at the moment.

The short answer is that it doesn't religiously follow any one style. The closest it comes to is Google's shell style, but the defaults are different - for example, the printer here uses tabs by default instead of Google's two spaces.

So, in practice, you could get very close to the Google style with something like:

    shfmt -i 2 -ci

That means "indent with two spaces and indent switch cases". I am not sure what they do about multi-line `&&`/`||`/`|` lists - you could look at the `-bn` option for that.

I am happy to document whatever we come up with in this thread.

**Comment by mvdan** [comment]
Friendly ping @notjames - did you have a chance to try out my suggestion above?

**Comment by notjames** [comment]
Oh, I just got this. I've been using the `-i 2` switch, but not the `-ci`. I'll try that this weekend and get back to you asap next week. Thank you for the comment back.

**Comment by notjames** [comment]
@mvdan I tried out your suggestion. It works for me. I'm not really sure that being conformant to any specific style is important as long as the user has the ability via arguments to get to the style they need/prefer. In fact, I personally like that better as I'm only partial to the google guide because the rest of the team is. There are some styling recommendations in that guide that I personally do not subscribe to.

**Comment by mvdan** [comment]
Great to hear. It's true that the Google standard is a style, not just a format. It enforces many things that don't belong in a tool that simply reformats programs.

I'm going to close this issue, adding tips to the README.
