### ISSUE TITLE
Allow quotes in arithmetic expressions

### ISSUE THREAD

**Issue by lollipopman** [mvdan/sh#223]
Bash evidently supports quotations in `let` expressions, allowing you to add spaces between operands, http://tldp.org/LDP/abs/html/arithexp.html. Would it be possible to add this support to shfmt?
```
$ shfmt << 'EOF'
> count=0
> let "count += 1"
> echo $count
> EOF
<standard input>:2:5: quotes should not be used in arithmetic expressions
```

Thanks, for making shfmt!

**Comment by mvdan** [comment]
`let` is a monster, really; Bash says it's a builtin, but it is treated like a keyword. For example, the following should be a syntax error if it were a builtin:

    let i=(3)

Builtins should just receive string arguments. That's why `echo i=(3)` errors.

Given this inconsistency, the parser here treats some "builtins" like let and export as keywords (this is what the README mentions). What this means is that the arithmetic expressions in let are parsed statically, just like with `$(())`.

This, however, brings us to quoted strings. Three solutions came to mind:

* Not allow quotes. That way, arithmetic expressions in the AST will *always* be fully parsed and simple. You'll never come across something that isn't a literal or an arithmetic expression, like `"count += 1"`.
* Allow quotes, simply expanding them (parsing what's inside of them). This could be confusing, however, and would mean that `shfmt` would get rid of your quotes.
* Allow quotes, and leave them be - then it is up to the AST user (such as a static analysis tool or the `interp` package) to run the parser on these quoted sub-expressions as necessary.

I chose to go with 1, because it's the simplest and cleanest for both me, the API, and the users. It is technically going against POSIX and Bash, but I must do that in some edge cases anyway (see the rest of the caveats section in the README).

Ultimately, my reasoning is that quotes in arithmetic expressions don't make sense. The only possible use for them (besides yours, which is spacing) is arithmetic expressions that are built at run-time, thus they cannot be parsed statically. Then I'd suggest using `eval`, which is the standard solution for when one needs to run a piece of shell code and cannot via simple variable substitution.

Having written all this, it is also true that I do bend over to support `declare` and `export` hacks. For example, the parser and interpreter support this, confusing the API and users:

```
$ a=b=c
$ echo $a
b=c
$ declare $a
$ echo $b
c
```

This is another instance of a "builtin" that re-runs the parser on its arguments.

Thoughts? None of the solutions are perfect, so I'm open to suggestions.

**Comment by lollipopman** [comment]
Let me preference this comment with stating that I am speaking as a shfmt user who hasn't yet dived into the code base:

From a readability  perspective, I do think spaces in let statements are nice:
```
let "CRIT_COUNT += 1"
# vs.
let "CRIT_COUNT+=1"
```
So my preference would be 2, if quotations could be preserved somehow, though you clearly state that keeping quotations would be difficult.

If it is too difficult to keep the quotation marks then I think I would probably choose 3 as a shfmt user, since the `let` expressions are usually short and hopefully correct.

If you stay with 1, and continue emitting an error, it might be worth considering taking an approach similar to shellcheck and emit unique codes, those are a great help for a user such as me to understand the rationale, e.g. https://github.com/koalaman/shellcheck/wiki/SC2035

**Comment by mvdan** [comment]
2 with quotes preserved could be an option, but it would require adding a special node just for this. Like `QuotedArithmExpr`. And it would also get more complex - what about single quotes? What about `let $'foo'`? And so on.

3 is certainly an easy solution on the side of the parser, but it adds quite a lot of complexity to the AST for its users.

Ultimately, I think the question that needs answering is whether we want to support `a='b + c'; let $a` too. If we do 2, multiple arithmetic expression parsing passes aren't needed. If we do 3, they are, and we support cases like `let $a` as well as `let "b + c"`.

Going back to consistency, we do the latter with `declare`:

```
$ gosh
$ declare "a=c"
$ echo $a
c
$ x='a=d'
$ declare $x
$ echo $a
d
```

So I'm currently leaning on 3. I guess that if anyone wants to be strict like I'm suggesting, they can always forbid parameter expansions and quotes in arithmetic expressions.

Another point - this would require that we too support this in all other arithmetic expressions, such as in `$(("foo"))` and `a["foo"]`. Indexes are a bit of a problem, as the AST currently defines quoted indexes as corresponding to associative arrays (string maps), while non-quoted indexes correspond to indexed arrays. So that could be a backwards incompatibility problem.

**Comment by lollipopman** [comment]
Going with 3 and keeping consistency with `declare` seems reasonable to me.

**Comment by mvdan** [comment]
Yes, it technically seems like the best long-term solution to me too. Just need to figure out the details of how to roll this out in a way that won't break backwards compatibility. Been bouncing ideas around in my head for the last few days.

**Comment by mvdan** [comment]
So, apparently the degree to which expressions can be constructed at run-time is ridiculous:

```
$ cat f
x='a=(2+'
y='4)'
((${x}3+${y}))
echo $a
$ bash f
9
```

But in any case, that's for the interpreter to worry about. The syntax package is simpler.
