### ISSUE TITLE
syntax: support for spaces after redirection operators

### ISSUE THREAD

**Issue by PeterDaveHello** [mvdan/sh#243]
Hi @mvdan,

Thanks for this awesome tool, I haven't known any of other shell script formatter before! Just wondering if it's possible to add a space before and after the redirection and read symbol so it'll be easier to read?

Thank you for your effort again!

**Comment by alok** [comment]
I second this. It's a lot easier to read IMO, and is consistent with the other operators like `&&`, `||`, and `&`.

**Comment by mvdan** [comment]
Thanks for bringing this up!

When I first designed the tool, I tried to use the most consistent and common style I could come up with. Slowly, I was pressured into adding a few flags, such as controlling the indentation or the placement of `&&` when split in multiple lines.

The reason I chose to not put spaces after redirection operators was following those principles. I believed this style was more common, and it seemed more consistent with the rest of the (bash) language. For example, one can do `>(cmd)`, but not `> (cmd)`, as `>(` is a token. Similarly, `> &2` would fail, as `>&` is a token.

Personally, I also slightly prefer having no spaces, since it's easier to tell which parts of a line are arguments, and which are redirections. But that's just personal preference.

Having said all this - I'm open to suggestions, although I'd prefer to keep the number of options in the tool at a minimum. We can't change the default right now, as that would break backwards compatibility. So I presume you'd be suggesting a flag/option to do this. Would the flag only apply extra spacing to redirect operators, or would it also apply elsewhere? Would it do `>& 2` too?

Please also take a look at the `-kp` flag, which lets you keep your own padding and vertical alignment. It basically means "only indent, but leave the rest of the whitespace as it is". I know it's a bit of a nuclear option, but for people or projects who have their own standards, it may be the best option.

**Comment by mvdan** [comment]
I forgot to mention - any proof that this style is popular or recommended by large organizations or projects would help me decide whether this is worth the extra complexity in the tool.

**Comment by PeterDaveHello** [comment]
Hi @mvdan,

Thanks for your explanation, I didn't notice about the part with `>&` and `>(`, now noticed that having no space in that cases is reasonable. Personally, I mean to have space for those without `&` and `(` but just `<<` or `>>`, and would like to have a flag to control it so that I can use this tool with different projects.

`-kp` is good to keep to original styles, for those cases having inconsistent styling, more powerful styling features would be super helpful :smile:

**Comment by alok** [comment]
@mvdan I just ran `find /usr -name '*.sh' | xargs grep '>>'` on my mac (which has a lot of homebrew packages installed, so it's probably representative enough), and pretty much all of them had the space.

**Comment by alok** [comment]
I'd suggest something like this for spacing rules.

Only bare `>` and `>>` have spaces applied, unless it's a redirection to file descriptors like `&1`, which has no space (seemed idiomatic based off the command iI ran above).

Redirection to `/dev/null` has no spaces, but this idiom seems to be unique to `/dev/null` and `&1, &2,&n` . Every other file has a space. I don't know if it's an idiom worth keeping. I'm also not that concerned with backwards compatibility (blame python 2).

**Comment by mvdan** [comment]
> -kp is good to keep to original styles, for those cases having inconsistent styling, more powerful styling features would be super helpful

Yes and no - this is useful, for example, if one wants to maintain consistent custom styling like:

```
foo bar   etc
foo baaar etc
```

So in a way, this is what I am suggesting. It's like running the tool in a more liberal mode. Perhaps it would be a good first step for a project that uses a style that differs from the ones this tool can enforce.

(now replying to both of your suggestions on how to design this)

Not doing it for cases like `>&1` and `>(foo)` isn't really a decision to make, as there's nothing to decide. If we add spaces, the program breaks.

I also assume we want this to apply to all redirection operators, not just `<<` and `>>`  - @PeterDaveHello's comment has me a bit confused.

As for doing no spaces for `>/dev/null` I think this is making the logic way too complicated for the users. What about `</dev/zero`? And what about `>/some/file` or `>some-file`? In my eyes, these should all be using the same style. If we are to add spaces, I believe we should be consistent, or at least have very simple rules.

**Comment by PeterDaveHello** [comment]
I mean because of  `> &1` and  `>  (cmd)` is invalid, right?

**Comment by mvdan** [comment]
> I'd suggest just putting spaces in every case where it's valid syntax. It's just easier to read.

Yes, that's more like what I was thinking. The issue then is proving that this style is common enough to warrant having such an option in the formatter. This is why I was asking if there are any large projects that use it, or if there is any style guide that suggests it.

> I mean because of > &1 and > (cmd) are both invalid, right?

You're just confusing me further now :) Yes, `> &1` is invalid, but `> some-file` is valid.

**Comment by alok** [comment]
A random sampling of some large project's shell scripts showed they all use a space

**Comment by PeterDaveHello** [comment]
> You're just confusing me further now :) Yes, > &1 is invalid, but > some-file is valid.

I mean to use space when it's valid ;)

**Comment by alok** [comment]
@mvdan So Classic Shell Scripting by Arnold Robbins uses spaces in redirections whenever it's valid syntax, so I move that shfmt should do that too.

**Comment by mvdan** [comment]
Thank you both for your input. Please take a look at #246, give it a go, and let me know if there are any issues or if the design seems wrong. If all goes well, I'd like to ship it with v2.5.0.

**Comment by mvdan** [comment]
2.5.0 with this feature came out a bit later than I imagined, but it's out now :)

**Comment by PeterDaveHello** [comment]
Thank you @mvdan
