### ISSUE TITLE
syntax: use single space before && and || 

### ISSUE THREAD

**Issue by PeterDaveHello** [mvdan/sh#244]
Quick question: Can we just use single space before `&&` and `||`?
`sh` seems to use two spaces just before `&&` and `||` in some situation

Thanks a lot.

**Comment by mvdan** [comment]
Two spaces before `&&` and `||`? Do you have an example? I can't think of a reason why it would do that.

**Comment by PeterDaveHello** [comment]
Not sure maybe if it's caused by `&>` or just a bug in some situation
```diff
-if type tmux &> /dev/null && [ -n "${TEST}" ]; then
-    tmux rename-window test > /dev/null &
+if type tmux &>/dev/null  && [ -n "${TEST}" ]; then
+    tmux rename-window test >/dev/null &
     if [ "$(tmux showw automatic-rename | awk '{print $2}')" != "on" ]; then
        tmux setw automatic-rename >/dev/null &
     fi
 fi
```

**Comment by mvdan** [comment]
When you provide examples to reproduce a bug, please include the command you used to format the script. I presume you used `shfmt -kp` to obtain that diff, which is expected since that's how that feature works - it keeps the alignment of certain tokens, such as `&&`.

It currently doesn't do that for redirect words, which is what I was suggesting in #243.

**Comment by PeterDaveHello** [comment]
@mvdan I'll remember that, and you are correct, `-kp` causes that, I didn't realize it properly before, thanks for your help！
