### ISSUE TITLE
Formatting Options/Do-Not-Format comment

### ISSUE THREAD

**Issue by dcsobral** [mvdan/sh#251]
As with some other tools, recognize a comment as indicating a section of code where no formatting should take place, or where different options should take place.

**Comment by alok** [comment]
This change actually does make sense to me.

**Comment by mvdan** [comment]
As for no formatting - this is trickier than it may seem. See #248.

As for different options - potentially doable, but it feels to me like this would greatly complicate the tool. Could you give some examples where this would make sense?

Lastly - if either of these were ever added, I imagine this would only be available at the top level. That is, one couldn't change the formatter in the middle of a command or in the middle of a subshell. Otherwise, this would mean large refactors in the parser and printer to allow parsing and printing incomplete programs, which doesn't seem like a good idea.

**Comment by alok** [comment]
I just realized I totally misread the intent of this. I meant that comments should not be reformatted. I then realized that comments aren't formatted anyway.

**Comment by dcsobral** [comment]
The one use case that always comes to mind is where the code needs a particular table-like formatting to make sense. Imagine, for example, a sequence of case statements, one per line, and each one sets a group of options, with options being vertically aligned. In tabular form, you can look up by case statement or by option.

It's useful on finite state machines and grammars, though the latter is not something one should be doing in shell scripts. FSA, on the other hand, is a very useful tool. I wish languages directly supported it.

**Comment by mvdan** [comment]
It seems to me like this would be easy to implement on top of the existing `syntax` package via a Go program. For example:

* Parse shell script into a syntax tree
* Find top-level comments that mark these printer modes
* Split the program into pieces
* Run the printer on each piece with the appropriate knobs

This seems like a fairly niche feature that would complicate the `shfmt` tool quite a bit, so I'd like to see this implemented by a third party first. I imagine that there could be lots of other higher level features one could add to such a tool, while they wouldn't belong to a simple formatting tool like `shfmt`.

If the implementation works well, the design is clean, and the tool becomes popular, we can always consider merging the code into this repository in one form or another.

**Comment by mvdan** [comment]
As said above - I think this should live as a higher-level tool, for example as part of a multi-language formatter or an IDE's formatting. Or, at least, it should start as an external prototype.
