### ISSUE TITLE
Reporting various potential mksh bugs

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#258]
Hi @mirabilos,

I can't find the issue tracker for mksh, and I don't want to email you about this, so I'm abusing this issue tracker to send you a few potential mksh bugs I've found lately. I'll use `dash` here for comparison, but this parser, `bash`, or any other shell should give the same result. I'll also use `$''` quotes, so I can use escape codes for newlines and so on.

1) invalid function names seem to be accepted sometimes.

```
$ mksh <<<'"foo"() { :; }'
$ dash <<<'"foo"() { :; }'
dash: 1: Syntax error: Bad function name
```

2) heredoc delimiters seem to be broken in R56 (this worked in R55, I'm pretty sure). This one is a bit dodgey, because the input is invalid UTF-8, so my parser complains about that. But most shells only read bytes, in which case the two bytes `$\xc8` are the delimiter. I think mksh should accept the program, unless it aims to understand UTF-8.

```
$ mksh <<< $'<<$\xc8\n$\xc8'
mksh: <stdin>[3]: here document '$' unclosed
$ dash <<< $'<<$\xc8\n$\xc8'
```

3) functions with no bodies.

```
$ mksh <<< $'foo()'
$ dash <<< $'foo()'
dash: 2: Syntax error: end of file unexpected
```

4) certain arithmetic operators on non-variables (using bash for comparison on this one as dash seems to do something weird):

```
$ bash <<< $'echo $(((a)+=b))'
bash: line 1: (a)+=b: attempted assignment to non-variable (error token is "+=b")
$ mksh <<< $'echo $(((a)+=b))'
0
```

5) missing index is allowed - this one might be alright though, if you allow empty expressions everywhere, like in `$(())`:

```
$ bash <<< $'echo $((a[]))'
bash: line 1: a[]: bad array subscript
bash: line 1: a[]: bad array subscript
0
$ mksh <<< $'echo $((a[]))'
0
```

**Comment by mirabilos** [comment]
Please do not use Github like this. It makes it very hard for me to answer and make sense. Issues are tracked by mailing to the miros-mksh mailing list, IRC, or, if you must, at Launchpad (see the end of the mksh manpage for details).

mksh <<<'"foo"() { :; }; foo' ← this just defines a function called “foo”

mksh <<< $'<<$\xc8\n$\xc8'  ← you have the wrong error message:
mksh: <stdin>[3]: here document '$�' unclosed

That’s because you likely have the syntax wrong… lemme try… why *do* you have those extra dollar signs in there, anyway? Hm, no, I can’t get a syntax working. I’ll look at this.

**Comment by mirabilos** [comment]
Functions with no bodies aren’t allowed, the syntax in SUSv4 is clear:

fname ( ) compound-command [io-redirect ...]

We support this, even 'fname() :' with no curly braces, and 'fname() ( foo )'

**Comment by mirabilos** [comment]
Arithmetics: let me handle the second one first: yes, empty strings, when evaluated in arithmetic context, evaluate to the number 0, so that’s quite correct (for a Korn shell). This is more than what POSIX requires, but not contrary to it.

$((…)) stuff: this syntax is beyond POSIX and thus dash, so no wonder it does “something weird” there. mksh just recognises that '(a)' is the same as just 'a' and does not remove the “it’s a variable” property from it. In fact, I’d consider this a bug in GNU bash, as POSIX sh $((…)) is supposed to work like C arithmetics (to my never-ending horror including 0777-style octals), and '(a)=b' is valid in C (often used in macros).

**Comment by mvdan** [comment]
> Issues are tracked by mailing to the miros-mksh mailing list

Noted - I will use the mailing list next time. I had been searching for "issues" and "tracker", hence how I missed it even on its website.

> this just defines a function called “foo”

I just realised that the POSIX spec isn't strict about this: `An implementation may allow other characters in a function name as an extension.`. So this is a bad one on my part.

> Functions with no bodies aren’t allowed, the syntax in SUSv4 is clear

I am precisely pointing out that mksh allows declaring a function with no body :)

> Arithmetics

I presumed I might be wrong about this one, but wanted to bring it up just in case.

**Comment by mirabilos** [comment]
Ah, misread that then. *shrug* mksh is not a strict POSIX checker. I may or may not (when I find the time, so probably not before retirement, should I survive long enough to see it) write a separate one (basically mposixsh, to be later extended with mksh extensions in a controlled, not inherited, way).

**Comment by mvdan** [comment]
:) I'll close this issue then, since you replied to all of them.
