### ISSUE TITLE
parse: (( should equal $(( in bash

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#26]
```
[manny@maxwell ~]$ cat t.sh 
((5==5))
[manny@maxwell ~]$ source t.sh; echo $?
0
[manny@maxwell ~]$ cat f.sh 
((5>6))
[manny@maxwell ~]$ source f.sh; echo $?
1
```
but shfmt is adamant about inserting a space between the leading double parens, probably due to 5979268 which fixed #16

**Comment by mvdan** [comment]
The issue is that we parse this as two nested subshells, not as an arithmetic expression. This is because `((` instead of `$((` is a bash feature, and the bash manual is just too big for me to read it all (whereas POSIX is actually kinda small).

I can add support for this, but this is the first POSIX Shell breaking code I'll be adding. So this forces me to start a posix compliance mode flag, since otherwise I would break either bash or posix.

**Comment by nshalman** [comment]
The good news I take from this is that if we avoid the bash-ism and use `$((` we should be able to sidestep this issue in our code base.

**Comment by mmlb** [comment]
Except that `$(( ))` has different return semantics:

```
[manny@maxwell ~]$ $((5==5)) && echo ok
bash: 1: command not found
[manny@maxwell ~]$ ((5==5)) && echo ok
ok
```

**Comment by nshalman** [comment]
Yeah, just noticed that and was about to delete my comment.

**Comment by mmlb** [comment]
```
if ((5 == 5)); then
    echo ok
fi
```
does what we expect in bash and does not get a space by shfmt, but I'm not sure if it'll stay that way.

**Comment by mvdan** [comment]
I'm fixing this, so no worries. The parser should accept any valid bash program, and it isn't right now in this case.

**Comment by mvdan** [comment]
Bash has all these little additions to POSIX and I'm sure I've missed many, so feel free to open more issues if you encounter more.

**Comment by nshalman** [comment]
Thanks!

**Comment by mmlb** [comment]
thannks @mvdan, will do.
