### ISSUE TITLE
syntax: add option to configure how many statements in a list can fit in a single line

### ISSUE THREAD

**Issue by tamalsaha** [mvdan/sh#261]
Thanks for this tool. In our shell script, we have lines like 

```
 	local cmd="docker build -t $DOCKER_REGISTRY/$IMG:$TAG ."
	echo $cmd; $cmd
```

We would like to not break lines like `echo $cmd; $cmd` into 2 separate lines. I did not see any flag to support this. Can this be supported?

**Comment by mvdan** [comment]
There was a similar suggestion here earlier: https://github.com/mvdan/sh/issues/250

The suggestion there was to add an option to never split statements. Yours seems to be related to minimum length. Do you have a strong opinion either way?

I'm not terribly convinced by either suggestion. The earlier one is all-or-nothing, and this one is based on a heuristic. Neither are bad ideas per se, but I only want to add new features and flags (which I'll have to maintain for a long time) if I'm sure they will be simple and useful.

Here's another point - would this apply to other statements like blocks and subshells? Or should this only apply within lists of statements? For example, suppose this line was under the threshold:

    foo() { bar; baz; }

Should it be turned into the following?

    foo() {
        bar
        baz
    }

/cc @dcsobral

**Comment by tamalsaha** [comment]
Thanks for the quick response.

> The suggestion there was to add an option to never split statements.

I don't think that makes sense, since I want to optionally disable line break.

Regarding the block statement, we have number of cases like

```
kubectl config current-context || { echo "Set a context (kubectl use-context <context>) out of the following:"; echo; kubectl config get-contexts; exit 1; }
```
Again one heuristic will be to a not break if # of statements is <= 2 .

I have seen linters from other languages support per line directive via comments. So, one generic way to do this can be:

```
 	local cmd="docker build -t $DOCKER_REGISTRY/$IMG:$TAG ."
	echo $cmd; $cmd # NOWRAP
```
This kind of looks ugly to me. But I can live with this. May be I would move to the right most column by auto formatting.

**Comment by mvdan** [comment]
> Again one heuristic will be to a not break if # of statements is <= 2.

I'm not sure I follow. Do you want that line you pasted to be broken into many, or not? When you said min length, I presumed you meant a number of columns, not a number of statements.

> I have seen that linters from other languages usually support per line directive via comments.

I'm really not a fan of directives, so I doubt I'll ever add those.

The problem, then, is teaching the tool when it is fine to cram many statements into a single line.

**Comment by tamalsaha** [comment]
> I'm not sure I follow. Do you want that line you pasted to be broken into many, or not? When you said min length, I presumed you meant a number of columns, not a number of statements.

I was trying to say that if a single line block `{}` has more than N statements then it is broken into many lines. N is a user configurable variable, with the default being 2. I am assuming the common use case to be like 

```
 do_some_test || { echo "test failed"; exit 1; }
```

**Comment by mvdan** [comment]
Ah, I see what you mean. I like this suggestion. I'll work on the implementation and see how it plays out.

**Comment by mvdan** [comment]
This can also be exposed in two different ways:

* Allow lists of up to N statements in a single line
* Lists of N statements or more get broken into one statement per line

Breaking of statements would always result in one statement per line, as the tool would otherwise do a poor job most of the time.

**Comment by tamalsaha** [comment]
This sounds good to me. I agree on `Allow lists of up to N statements in a single line (default 1)` .

**Comment by mvdan** [comment]
It would be great if some value meant that `foo() { bar; }` always gets rewritten to be multi-line. That is, like how `gofmt` works.

Do we want to have a mode to allow any number of statements on a single line? I would say not. At that point, the user should be using the minify flag. And if they really edit code like that, I'm not sure why they use a formatter anyway.

We could make the `0` value for the "allow lists of up to N" option to always separate statements into their own lines. I have no idea what to call the flag, or how to fit all this in one sentence, though.

**Comment by tamalsaha** [comment]
How about these flags ?

```
- max-statement-per-line
- max-statement-per-line-in-a-block
```
Both can have a default value of 1. In my case, I can set this to 2 for both cases. You don't need the special case `0` value. What do you think?

**Comment by mvdan** [comment]
I presume you're suggesting two flags so that there's no need for a 0 value special case. Note, however, that the shell's idea of a block is blurry.

For example, `if foo; then bar; baz; fi` has no blocks. Same for switch cases and for loops, and it is even possible to write a function declaration without a block. This is why I was saying "statement lists" instead of "blocks".

I'd still prefer one flag, simply to avoid verbosity and problems if both flags are used together.

My current thinking is something like:

```
-sts uint   lists of up to N statements allowed on a line
            (0 to always use separate lines, default 1)
```

**Comment by tamalsaha** [comment]
Sounds good to me.

**Comment by mvdan** [comment]
Implementing this will be more difficult than I thought, because we want it to support sub-lists too. For example, `-sts 2` would keep the code below intact:

```
foo
bar; baz
etc
```

I still want to do this, but the refactor would be pretty large and I'd like to get 2.5.0 out sooner and with less risky changes. I'm pushing this back to 2.6.0 for now.

**Comment by patrickvane** [comment]
A fork that will never split statements can be found here: https://github.com/patrickvane/sh/blob/patrickvane/shfmt.exe
The option is "-ns" (never split). 
To use it in phpstorm etc, make a cmd like this: https://github.com/patrickvane/sh/blob/patrickvane/shfmt.cmd

**Comment by tamalsaha** [comment]
Thanks @patrickvane . Have you considered opening a pr?

**Comment by patrickvane** [comment]
> Thanks @patrickvane . Have you considered opening a pr?

That was my initial plan, but the PR was not accepted for unknown reasons: https://github.com/mvdan/sh/pull/585

The reason was something along the lines of "not high on my priorities", even though the code is already done. This is a wild guess, but I think the author wants to force his formatting style on others which he tries to achieve with this tool/formatter. I'll maintain my fork with the latest updates plus with additional options included, such as the -ns option. 

I hope that helps. I couldn't use the formatter with the line splitting, I think many people run into that problem from what I've seen and heard. I hope my fork will be the solution for many for that problem.

**Comment by mvdan** [comment]
> was not accepted for unknown reasons

I thought my reply was pretty clear - this issue is about configuring how many commands can fit in a single line, not about allowing an unlimited amount of commands to be crammed into a single line. Your pull request disabled that functionality entirely, which sort of defeats the purpose of a code formatter.

> even though the code is already done

I hope that, with time, you will understand that open source is not just about code. When you send upstream a new feature, you're asking them to review it and maintain it forever.

> the author wants to force his formatting style on others which he tries to achieve with this tool/formatter

I'm not sure how to respond to this. I've spent countless hours on this open source project on my spare time, so such accusations really ruin my day.

Yes, the formatter is somewhat opinionated. I don't want it to end up with a hundred options, like [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) or `man indent`. That necessarily means that, for some people, it won't be quite what they want, and I'm okay with that. There's a tradeoff to be made between "try to please as many people as possible" and "keep the tool simple and maintainable". This project is maintained on a few hours of my time per month, so it's definitely towards the latter end ofthe spectrum.

> with additional options included

Beware that more formatting options make testing all the edge cases exponentially harder. With two formatting options, you have four combinations to test. With a dozen options, you already have over four thousand combinations to test on various inputs and outputs.

> I think many people run into that problem from what I've seen and heard

From what I've seen in this issue tracker, yes, some people want some sort of feature like that. But, as it stands, this issue has had a single thumbs up in the past two years, compared to seemingly more popular issues like https://github.com/mvdan/sh/issues/80. I can only prioritise the issues that people actually give feedback and vote on.

**Comment by patrickvane** [comment]
> Your pull request disabled that functionality entirely, which sort of defeats the purpose of a code formatter.

A lot of people use the code formatter to format their whitespace (like indention etc). Making an option to disable the line splitting doesn't make the formatter useless, it doesn't defeat the purpose of the code formatter. 

> I hope that, with time, you will understand that open source is not just about code. When you send upstream a new feature, you're asking them to review it and maintain it forever.

Running a project also means you'll take other people's issues into account. In this case, you completely ignore people's issues/problems simply because you aren't run into them yourself (yet). Also the point of having an open source project means others can fork it and do it their own way, which is what I'll be doing. 

> Yes, the formatter is somewhat opinionated. 

It's 'opinionated' (or rather intolerant) to the point of it causing problems to people. I don't see how this is a good thing. 

> Beware that more formatting options make testing all the edge cases exponentially harder. With two formatting options, you have four combinations to test. With a dozen options, you already have over four thousand combinations to test on various inputs and outputs.

That's true, and it's a trade-off for certain. In this specific case, I'd say it's worth it (as I can't use it otherwise), your opinion might be different. A fork of this project is then a good solution if different opinions/philosophies can't work together in the same project. 

> But, as it stands, this issue has had a single thumbs up in the past two years, compared to seemingly more popular issues like #80.

But that's achievable by people themselves (if the formatter doesn't undo their own manual formatting). The formatting doing that for them is an enhancement, it's not a problem they're running into. I would prioritize problems and enhancement requests differently. 

> I can only prioritise the issues that people actually give feedback and vote on.

That's true and that makes sense, especially when time is an issue.

**Comment by kaey** [comment]
Examples in OP are unconvincing:

```
echo $cmd; $cmd

Should instead be

runx() {
    echo "$*"
    "$@"
}

runx $cmd
```

```
do_some_test || { echo "test failed"; exit 1; }

Should instead be

die() {
    echo "$*" >&2
    exit 1
}

try() {
    "$@" || die "failed: $*"
}

try do_some_test
```

gofmt has proven that formatters do not need a single option.
Don't add any more of those, pretty please.

**Comment by mvdan** [comment]
> it doesn't defeat the purpose of the code formatter.

We agree to disagree :) a tool that just tweaks whitespace is little more than an indentation tool, which Vim and other editors already implement for most formally defined languages.

> In this case, you completely ignore people's issues/problems simply because you aren't run into them yourself

I strongly disagree; I've clearly laid out my thoughts as to why I there is a tradeoff at play with every new feature and option. I'm not sure why, but you seem determined to think that I'm employing malice in my thought process.

> I'd say it's worth it (as I can't use it otherwise)

A formatter is strict by nature, and we've agreed that we can't add all options under the sun nor please everyone. If you have strong convictions and can't be flexible on any of them, I would personally suggest that you shouldn't use a general-purpose formatter in the first place. It will be easier if you just maintain your particular format as you see fit, and use simpler tools to help you like an editor's auto-indentation.

Initially, the tool did indeed have zero formatting options. There was strong opposition to that from users; I think some of the options we added, like `-i` and `-bn`, probably make sense. With time, I'm less and less convinced that options such as `-kp` or this one are a good thing; they just reduce the formatting's strength. If someone wants to reuse my work and maintain a fork of shfmt which has thirty formatting options, by all means please do - but I'm sure it's not something I want to do.

**Comment by patrickvane** [comment]
> a tool that just tweaks whitespace is little more than an indentation tool, which Vim and other editors already implement for most formally defined languages

Weird, your editor can auto indent etc every language out there? I don't think the jetbrains editors can do that (which I use for php, java and shell/bash). You can select lines yourself and press tab to indent them, but that would also indent string contents (so possibly file contents which could mess things up). 

Besides that, when you use spaces for indention, then sometimes you're a space off without really being able to tell for certain, so having a formatter for that prevents you from having to double check everything (normally I use tabs for indention with which you don't have that problem, but for shell/bash it makes more sense to use spaces in my usecase, as then I can copy paste it into putty to test parts out, you can't do that with tabs as tabs have a special meaning in the terminal). 

Anyway because jetbrains has recently build in support for shfmt I decided to use that, only to find out it doesn't just fix the spacing/indention/etc, but that it also reworks your code completely making it unreadable in several cases. Even for simple cases like: `if a && b && { c || true; } && d; then`

Anyway I'll maintain a fork that is mostly focused on just working for spacing/indention, so basically without line splitting, as that seems to be the only option I have right now, I don't know of any jetbrains plugin or any shfmt-compatible alternative that can do that currently. 

> Initially, the tool did indeed have zero formatting options

Yeah most formatters have pages and pages of options, this one is the oddball out, not sure how or why. I don't care much for it, I just want the whitespace formatting to work without it changing anything else about my code, it's sad the jetbrains editors don't provide this by default but at least with the fork I now have a way to get it to work regardless.

**Comment by powerman** [comment]
@kaey:

> Examples in OP are unconvincing:

How about examples in #564?

**Comment by kaey** [comment]
>but that it also reworks your code completely making it unreadable in several cases. Even for simple cases like: if a && b && { c || true; } && d; then

shfmt doesn't change this line

>How about examples in #564?

Ok this makes scripts safer. That means current shfmt behavior is wrong - it changes safe scripts to unsafe. Hiding safe behavior behind an option is definitely wrong in my book.

I see 2 realistic paths here:

1. document current behavior in caveats and recommend using `main() {...; exit $? }` as suggested by @theclapp 
2. special case `...; exit ...` pattern to not be formatted and, again, document it in caveats

**Comment by dcsobral** [comment]
I think an important point of #564 is that these two things are not
semantically the same:

a; b

a
b

-- 
Daniel C. Sobral

**Comment by mvdan** [comment]
Thanks for bringing up #564 again; I've reopened one since I think defensive programming is a different matter.

As far as I can tell, the thread here is mainly about the semantics of two commands being tied together and separate from other commands. That is:

```
foo
echo bar; bar
baz
```

Personally, I would just use empty lines to clarify the separation:

```
foo

echo bar
bar

baz
```

If that is too verbose for you, that's a valid style preference, but this tool does not aim at pleasing everyone's personal style. It aims at being very consistent and predictable. Any change I can think of along the lines of removing line splitting, or making it tolerate two commands in a single line, would just make the style less consistent and the tool generally less useful. After all, it's impossible for the tool to know if two commands in a single line were meant to convey some information or grouping, or if it was just bad formatting.

**Comment by dcsobral** [comment]
Having the two commands on the same line is not simply organization. Shell
will read the source code from disk line by line, so if you have commands
on the same line they are safe from changes in the file, whereas commands
on consecutive lines are not.

The case in question is "a; b" where "a" is either long running or may
cause the source to be changed, and "b" does tear down/clean up. If on
consecutive lines, it is not guaranteed to run.

**Comment by mvdan** [comment]
Right, and I'm trying to focus that security/correctness aspect into #564. Note that the original issue content did not mention this at all.

The problem, though, is that if the "cleanup" command can be anything, then we can't know what pairs of commands on a single line are truly about cleanup.

So if your argument is that we should leave any pairs of commands alone, how should we format code as follows?

```
# many of them at once, not just a single line
foo; bar
baz; etc
long; body

# not just simple commands
{}; {}
if foo; then bar; fi; baz

# should we split this into three lines?
foo; bar; baz
```

**Comment by dcsobral** [comment]
I'd never split commands separated by semicolons into multiple lines.That
is fine for most languages since there's no distinction in them between
statements on the same line and statements on separate lines. That's not
the case for shell scripts, even if there's no difference under most
circumstances, so a formatter shouldn't be touching it.

-- 
Daniel C. Sobral

**Comment by mvdan** [comment]
>  a formatter shouldn't be touching it.

If you mean "never split lines", I think that goes too far (see the previous discussion). A formatter becomes pretty much useless if I can cram an entire 10KiB shell script into a single line, and the formatter doens't do anything about it.

**Comment by dcsobral** [comment]
As a contrived example, that's true. Notice, however, that such a script
has a different semantic than the same script spread across multiple lines.
It could rewrite itself without changing the code being run, for example.
To go to the other end of contrived examples, a formatter which breaks
programs it formats is useless as well.

As it happens, I've never used shfmt with the intent to split lines, and
I've been often annoyed by it when it happened, so there's definitely more
use to it than splitting lines.

**Comment by mvdan** [comment]
Thanks, that's helpful. We seem to be converging on that this isn't about personal preference, but about semantics. I agree that the current situation is unfortunate. But I also think that turning line splitting off entirely would be a pity; it's often a useful feature.

I hope there's some sort of compromise here that would prevent breaking reasonable uses of single-line commands, without also making the formatter significantly less useful for people who don't depend on the difference.

I'm inclined to merge this issue with #564, since that issue was indeed about the semantics, and this issue as a pretty lengthy backstory that just isn't all that relevant to the underlying issue.

**Comment by dcsobral** [comment]
I don't like #261 much anyway. There hasn't been much defense of it on its
own merits.

**Comment by mvdan** [comment]
Agreed. Let's move the discussion to #564, then :)
