### ISSUE TITLE
interp: can't echo \ on Windows

### ISSUE THREAD

**Issue by antylama** [mvdan/sh#291]
In Windows, gosh print dots:
```cmd
C:\Users\marcin\go\bin>gosh.exe
$ echo \\
.
$ echo \\\\
.
$ where echo
C:\Program Files\Git\usr\bin\echo.exe
```

I'm using echo from Git for Windows (but it's probably not a problem).

In GNU/Linux work's as expected.

**Comment by mvdan** [comment]
Been debugging a bit. This is because the interpreter thinks that `\` is a globbing expression, and thus it ends up matching the current directory. When the current directory is printed back as a relative path, we end up with the dot.

That also explains why many path separators print the same :)

This is certainly broken. It's just a bit tricky to get right, as backslashes on Windows are **both** a special character for globbing, and a path separator. For example - what should `echo foo\*` do? On Linux, it should definitely print `foo*` always. On windows, it could glob the equivalent of `foo/*`, or just print `foo*`.

I'm going to go with the safer route of giving priority to Windows path separators. So one can do `echo foo\*` if they want globbing, and in the rare case where a backslash on Windows actually meant escaping, they can use single quotes - `echo 'foo*'`.

**Comment by antylama** [comment]
For me it's OK when gash allow's only: `/` for directory separators, and optionally `\\` as single directory separator.
