### ISSUE TITLE
syntax: partial parsing in JS

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#294]
Running `bash` interactively, one can write code over multiple lines without `\`, because it recognises whether the 'final context' has e.g. unclosed quotes, or a `do` without `done`. The prompt changes to reflect this.

Can your parser be used in this way?
That is, is there a 'partial parse-tree' one could inspect to determine whether further input is required?

I'm actually interested in the javascript module, but first things first.

**Comment by mvdan** [comment]
It is possible - you can play with `gosh`, which has an interactive mode which should work just like any other shell's. It parses one statement (full command) at a time. The code is here: https://github.com/mvdan/sh/blob/master/cmd/gosh/main.go#L89

The API used is this one: https://godoc.org/mvdan.cc/sh/syntax#Parser.Stmts

I haven't exposed this in the JS package, simply because I'm not sure how to. I'd need some JS equivalent of `io.Reader`, so that I can read piece by piece without having the entire input in memory. Ideally, the other APIs like `Parse` and `Print` would also use streams and not strings.

I had an interesting discussion with different kinds of streams with a helpful reader on Hacker News a while ago: https://news.ycombinator.com/item?id=17084260

The tricky part is that I want the JS package to be portable, so it should work on browsers and not just Node. You probably know more JS than I do, so any input or suggestions are welcome.

**Comment by rob-myers** [comment]
Nice.

I see `gosh` handles e.g. the case `echo "f` then `oo"`, but not `echo "foo"; echo "b` then `ar"`.
Does `Parser.Words` handle the general case?

Concerning JS, I'm trying to run bash inside the browser (using a simplified notion of process, inode etc). To execute code I'd use your parser, transpile into my own language, construct an iterator, then iterate it.

To do so interactively, I need to send some possibly-partial code to the parser and either (i) receive the induced AST, (ii) receive information that e.g. there's an unclosed quote in the 'final context', or (iii) have an error thrown.

That might be preferable to choosing a stream implementation anyway?

**Comment by mvdan** [comment]
> I see gosh handles e.g. the case echo "f then oo", but not echo "foo"; echo "b then ar".

Huh. This just seems like a bug. Could you file it?

> Does Parser.Words handle the general case?

This API reads one word at a time, not one command at a time. It's not more general - it's just different. For example, on the input `(foo;`, `Stmts` will expect more input, and `Words` will just error.

> To execute code I'd use your parser, transpile into my own language, construct an iterator, then iterate it.

FYI, there's a shell interpreter in the `interp` package. I don't think I'll make it available in the JS code soon though, as I'm currently refactoring big chunks of it.

> That might be preferable to choosing a stream implementation anyway?

So you're saying, instead of a JS API like `Stmts(io.Reader, func(*Stmt) bool) error`, one like:

    Stmts(input string) ([]*Stmt, error)

Then, it would return any fully parsed statements, and an error if it encountered one. If given partial inpupt, the next call would finish the statement.

I realise this API is more complex, and that's why I wanted some equivalent of `io.Reader` we can use with regular JS callbacks.

**Comment by rob-myers** [comment]
A method to detect if further input is warranted (`Incomplete`) would be greatly appreciated, although I'd need it exposed in the javascript module too.

I know of no npm module providing such functionality.
Thanks for considering it!

Btw, I am bothering to write an in-browser interpreter because I want to _animate_ bash. I already have a lot of the code in place, where the UI terminals use [xtermjs](https://github.com/xtermjs/xterm.js).

**Comment by mvdan** [comment]
Thanks for the feedback. The added API would be exposed in the JS package, of course. I'll try to have this finished up over the weekend.

**Comment by mvdan** [comment]
I'm currently sitting at an awkward spot with GopherJS, the Go to JS compiler I use to produce the NPM package.

I depend on a feature that was never merged into upstream for unknown reasons: https://github.com/gopherjs/gopherjs/pull/790

However, Paul's fork is currently lagging a bit behind upstream, so it doesn't seem to fully work with Go 1.11 yet.

I'll wait to see if that can be worked out in the next week. If not, I'll simply push an update for the NPM package using Go 1.10. That's not ideal, but it's still a version of Go we currently support.

**Comment by rob-myers** [comment]
The quoting-fix seems to have introduced an issue:

```
~$ gosh
$ echo foo
foo
$ 
foo
$ echo bar
foo
bar
$
```

The second and third `foo` shouldn't appear.

**Comment by mvdan** [comment]
Thanks for noticing - just a silly bug, not caught because I didn't add enough tests.

**Comment by mvdan** [comment]
Here's another twist - `Parser.Stmts` and `Parser.Incomplete` aren't enough API to implement an interactive shell either. They break down in some cases, like:

* Pressing enter multiple times
* Single statements that are long and require multiple reads, but had no newlines in them
* Empty reads from standard input

To handle all of these edge cases, one needs lower-level access to the parser, so I'm adding a high-level API for parsing statements interactively. We can then expose that via JS.

`Parser.Incomplete` will probably stay though, as it's part of this new API and can be useful for other things.

**Comment by mvdan** [comment]
@rob-myers please take a look at the new version: https://www.npmjs.com/package/mvdan-sh/v/0.2.0

I realise there's one open JS issue left, which I'll likely fix in the next version. Please test and report more issues if you encounter any :)
