### ISSUE TITLE
interp: unset local variables misbehave

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#318]
```sh
~$ gosh
$ x=foo
$ bar () { local x=baz; echo $x; unset x; x=qux; echo $x; }    
$ echo $x
foo
$ bar
baz
qux
$ echo $x
qux # should be foo, according to bash
```

In other words, when you unset a local variable in bash it remains local.

**Comment by mvdan** [comment]
Thanks for the report. Variables in bash are an endless source of work.

**Comment by rob-myers** [comment]
Yeah, sorry for the endless issues.
If you've had enough of them just say!

**Comment by mvdan** [comment]
Upon closer inspection, this behavior seems badly designed to me. I can't find any mention of it in `man bash` or any other official bash documentation.

The closest I could find is http://wiki.bash-hackers.org/commands/builtin/unset#scope, which reverse-engineers what goes on when one unsets a local variable.

This will be very tricky to fix, because right now I treat unset variables as actually nuked; that includes the information about whether a variable was declared as local.

**Comment by mvdan** [comment]
Actually not as tricky as I thought, but still required to redesign how we internally represent unset variables.

**Comment by rob-myers** [comment]
Here's a similar issue:

```sh
~$ gosh
$ export x=foo
$ bar () { local x; export x=baz; gosh; }        
$ bar   
$ echo $x
baz
$ exit
$ echo $x
baz # should be foo, according to bash
```
