### ISSUE TITLE
syntax: rethink escaped newlines

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#321]
This is a problem with the non-interactive parser.

The string `'echo "foo\\\nbar"'` yields a `CallExpr` with two args.
- A literal `echo`.
- A `DblQuoted` with a literal `foo\↵bar`.

The second literal should instead be `foobar`.

**Comment by rob-myers** [comment]
Whoops, made a mistake somewhere.

**Comment by mvdan** [comment]
This is somewhat expected. The syntax tree needs to keep the escaped newline information somewhere, as otherwise it wouldn't be possible to print it back out without joining lines.

This may be confusing because the parser does the opposite for unquoted literals - escaped newlines are just dropped there. This is because the following is valid shell:

```
whi\
le true; do
   ...
done
```

So my strategy was to skip escaped newlines in unquoted literals to simplify that.

What we then do is remove these escaped newlines from literals when expanding them into strings: https://github.com/mvdan/sh/blob/bf9b1b6769b4e85be4c2e226eba2e347bd2eb4b3/expand/expand.go#L386

I realise that the way things are currently done is inconsistent and a bit inaccurate. Bear in mind that this was designed as an after-thought in the early days, before I had a better understanding of how shells work.

I'm thinking that a better approach would be to parse these literals as separate parts. That is, `"foo\\\nbar"` would be parsed as two literals within double quotes, one containing `foo`, and the other `bar`. And the printer would be able to keep that escaped newline, since it can know that the second literal starts in a line that's not the same as the first literal's end line.

I don't know if that approach would work well for unquoted literals too; I'd have to try and see. Thoughts?

For now, you should do the same that the `expand` package does, and remove those escaped newlines yourself.

**Comment by rob-myers** [comment]
I agree that the parser should preserve all syntactic information.
Currently I replace `'\\\n'` by `''` in each literal, as you suggested.

Given interactive input `echo "foo\\\nbar"`, what will the literals in `DblQuoted` be?
Currently there is only one with value `'foo\↵bar'`.

How would they be handled by the interpreter?

**Comment by mvdan** [comment]
The interpreter strips the escaped newlines within double quotes, as I showed in a previous comment: https://github.com/mvdan/sh/blob/bf9b1b6769b4e85be4c2e226eba2e347bd2eb4b3/expand/expand.go#L386

I need to revisit this; I'm still not sure what the best way to handle all escaped newlines would be. Ideally it would be a way that's consistent, keeps the original syntax information, and makes it simple for the formatter and interpreter to do their job.

**Comment by mvdan** [comment]
@rob-myers it took a number of evenings tinkering with it, but I finally came to a conclusion that makes me happy. I basically implemented this approach that I came up with last November:

> I'm thinking that a better approach would be to parse these literals as separate parts.

As you can see in the commit above, the `expand` package no longer has to remove escaped newlines. Your code should now be simpler too.
