### ISSUE TITLE
_js: add a way to construct nodes

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#331]
I work with a JSON version of your nodes, stripped of the internal structure.
This means I can't use `NewPrinter.Print` to print all, or some of, the parse tree.

Would it be possible to expose the node's constructors?

**Comment by mvdan** [comment]
I think what we've discussed in #298 and #330 would cover this. A node in JS would simply be an object with its original fields and a `type` field, and hopefully methods too.

Then, you could use that node in API calls such as `NewPrinter().Print(...)`. Equally, you could construct your own node as a plain JS/JSON object and pass it there. Just like in the current JS package, that plain node object would be converted to the internal node representation, so that the internal code can be run successfully.

What I mean by this is - once I've rewritten how nodes are represented in the JS package, there likely won't be a need for a constructor function.

**Comment by rob-myers** [comment]
Makes sense, thanks.

**Comment by rob-myers** [comment]
I have some questions:

- Given a parse-tree in JSON, would I be able to print sub-trees whose root is e.g. a `Stmt`, `Command` or `WordPart`?
- If so, would the output contain whitespace up to the first source-map position?
- Finally, would it be possible to print a manually built tree without specifying the source-map?

**Comment by mvdan** [comment]
1) Yes. See https://godoc.org/mvdan.cc/sh/syntax#Printer.Print
2) The output shouldn't have leading nor trailing whitespace, except when printing a file, in which case a trailing newline is added. Also partially documented in that link above.
3) If by source-map you mean position information, yes. It will format the code as if the input had all been on a single line.
