### ISSUE TITLE
syntax: DeclClause fields are inaccurate

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#332]
Given unset variables `x`,`y`, then `bash` behaves as follows:

```sh
~$ declare $x=$y
-bash: declare: `=': not a valid identifier
```

However:
- `NewParser.Parse` does not throw an error.
- `gosh` fails with error `panic: variable name must not be empty`.

**Comment by mvdan** [comment]
The issue here, as you've discovered, is that Bash's `declare` can evaluate its arguments at run-time, not just statically. This is why the parser accepts any argument that is a valid word. I'll reply to all the points in order.

1) The `gosh` panic on `declare $x=$y` is definitely a bug. I'll fix that.

2) The parser needs to accept `declare $x=$y`, however. For example:

```
$ x=foo y=bar; declare $x=$y
$ echo $foo
bar
```

3) You're right that the `DeclClause` fields are a bit broken. One can't assume that all the assignments in the `Assigns` fields are actually that, and not options. In fact, I even got this wrong in the interpreter.

The node definition is definitely imperfect, but I'm not sure how to improve it. After I explain point 4 you'll see why.

4) You can turn off `declare` parsing by parsing a script as POSIX shell instead of Bash. The reason is because even though Bash says that `declare` is a builtin, it's actually a keyword - it's parsed in a custom way, different than all other commands:

```
$ declare foo=(bar baz)
$ mydeclare foo=(bar baz)
bash: syntax error near unexpected token `('
```

So the declare node needs to have a list of assignments somewhere, to support Bash arrays (lists and maps) properly. Otherwise, we could just make the declare node have only an `Args []*Word` field, or just be a regular command like any other via `CallExpr`.

Joining 3 and 4: perhaps the simplest fix would be to fold `Opts` into `Assigns` as naked assignments, so that `declare -x foo` would parse almost identically to `declare $v foo`. Then, we'd document that any assignment in that list that is naked (i.e. doesn't begin with a literal `validname=`) could be an option if it begins with `-`.

Perhaps a way to clarify further that some elements of `Assigns` may not be assignments would be to call it `Args` instead. `Args []*Assign` would be a bit contradictory, but at least it would reflect reality better. We can definitely do a change like this one for v3.

**Comment by mvdan** [comment]
> Perhaps you could provide an additional array for ambiguous cases?

I forgot to address this point. I personally think this would complicate things further - I'd prefer a single `Args []*Assign` field than three lists. Either way, interpreting the arguments would require a bit of code. But in the three field case, certain operations like finding the first or last argument would be unnecessarily complex.

**Comment by rob-myers** [comment]
> The parser needs to accept `declare $x=$y`.

Certainly. I forgot about the static parsing, yet again.

> You're right that the `DeclClause` fields are a bit broken. One can't assume that all the assignments in the `Assigns` fields are actually that, and not options. In fact, I even got this wrong in the interpreter.

FYI, I currently patch `DeclClause` by:
- moving any `Assigns` with `-` or `+` prefixed names into `Opts` by converting them into a `Word`.
- moving any `Assigns` with null names into another array `others: Word[]` by taking their `Value`.

> You can turn off `declare` parsing by parsing a script as POSIX shell instead of Bash.

Good to know, but I want to use your bash parser.

> So the declare node needs to have a list of assignments somewhere, to support Bash arrays (lists and maps) properly. ...  perhaps the simplest fix would be to fold `Opts` into `Assigns` as naked assignments, so that `declare -x foo` would parse almost identically to `declare $v foo`. Then, we'd document that any assignment in that list that is naked (i.e. doesn't begin with a literal `validname=`) could be an option if it begins with `-`.

Simple is good.

- Will the parser throw an error for the invalid command `declare foo -x`?
- Will the parser enforce `declare [opts] [-p] [name[=value] ...]` as much as it can?

I guess one could have overridden `declare` by a function, so these errors aren't certain.

> Perhaps a way to clarify further that some elements of `Assigns` may not be assignments would be to call it `Args` instead.

Sounds good too.

**Comment by mvdan** [comment]
> Good to know, but I want to use your bash parser.

Unfortunately there's no good solution here. If `declare` was truly a bulitin like any other, we'd likely not parse it like a special node.

Not treating it as a keyword will break some programs, like I showed above. It seems to me like specifically turning off the parsing of `declare` would break with Bash, so it shouldn't really be bash parsing.

Perhaps look at `LangMirBSDKorn`, which parses like `mksh`. That's the shell used on Android. It has quite a few features that people are used to in Bash, but no arrays, so `DeclClause` doesn't show up.

> Will the parser throw an error for the invalid command `declare foo -x`?

Good question. My initial guess is not, since we parse arguments, and not options and declarations. The interpreter will need to check for invalid flags anyway, so it seems wrong for the parser to do that for simple arguments too.

> Will the parser enforce `declare [opts] [-p] [name[=value] ...]` as much as it can?

I presume the answer here would be the same. I'd presume not. The only point of the future `DeclClause` would be to allow having assignments as argumeents, to support parsing `declare foo=(a b c)`.

> I guess one could have overridden declare by a function, so these errors aren't certain.

Correct. So we want to do as few assumptions as possible.

--

A completely different approach here would be to take the route we did with arithmetic expressions. There, we support `x=123; echo $(($x))`, but not `x='1 + 2 * 3'; echo $(($x))`.

Similarly, we could support `x=name; declare $x; export $x=value`, but not `x=name=value; declare $x`. We would also require all options to be literals beginning with the `-` character.

This would align with the "sane shell" and "static parsing" mantra that the rest of the parser employs, but it would further break with Bash. I'd have to investigate if anyone does abuse `declare` to evaluate assignments at run-time. Any ideas?

**Comment by rob-myers** [comment]
Ok, I now understand why `declare` (and friends) must be parsed separately, given your static-parsing approach.

Also, thanks for sorting #318 i.e.
```sh
~$ gosh
$ x=foo
$ bar () { local x; unset x; x=baz; }
$ bar
$ echo $x
foo # which agrees with bash
```

**Comment by mvdan** [comment]
I went with my original approach to merge the Opts and Assigns fields into Args. Turns out to be a nice simplification of the former approach, and we don't lose anything.
