### ISSUE TITLE
Feature request: formatting a line range

### ISSUE THREAD

**Issue by infokiller** [mvdan/sh#333]
It's often useful to format only a range of lines in a file and not the entire file. This can be currently simulated by passing shfmt only the selected lines, but then shfmt doesn't have the other context, so it's not ideal.

Thanks!

**Comment by mvdan** [comment]
I'm not sure I understand why this would be useful. Why don't you want parts of a file to be formatted?

**Comment by infokiller** [comment]
Consider the following (line numbers added).

```shell
1: function foo() {
2: if [[ -n $VAR ]]; then
3: echo "VAR exists"
4: fi
5: }
```

If you want to format only lines 2-4, the correct formatting with 2 space indent is (note the leading spaces):
```shell
  if [[ -n $VAR ]]; then
    echo "VAR exists"
  fi
```

However if only these lines will be passed to shfmt, there will be no indentation, since it's not aware of the enclosing function.

**Comment by mvdan** [comment]
> This is mainly useful when working on files in existing codebases that don't have proper formatting. In these cases, some people prefer to only format the new code, in order to keep the commit small and focused.

Could one not reformat the files in a first commit, then do the small changes later? That's almost always a better solution, as you don't mix features or bugfixes with automated formatting changes.

If this is needed for an IDE or plugin, what does it do with formatting programs that don't have this kind of option, like `gofmt`?

> Yes, for example yapf and clang-format both support it (via a --lines argument).

That option leaves some unanswered questions. Is it input or output line numbers? Does the program reformat entire files, then recover original lines based on the ranges? Or if formatting only happens for the nodes within the ranges, what happens if a node is cut in half?

In other news, I don't see a simple way to implement this that will be straightforward to implement and maintain.

**Comment by infokiller** [comment]
> > This is mainly useful when working on files in existing codebases that don't have proper formatting. In these cases, some people prefer to only format the new code, in order to keep the commit small and focused.
> 
> Could one not reformat the files in a first commit, then do the small changes later? That's almost always a better solution, as you don't mix features or bugfixes with automated formatting changes.
Perhaps one could, and I know that I personally would prefer it, if only because I like automated consistent formatting everywhere. This actually [came up](https://github.com/google/vim-codefmt/pull/107#discussion_r238961231) in a PR I sent to integrate shfmt with a vim formatting plugin.
> 
> If this is needed for an IDE or plugin, what does it do with formatting programs that don't have this kind of option, like `gofmt`?
At least in the case of `vim-codefmt`, only the line range is sent to the formatting tool, ignoring the other context, but as you can expect that doesn't always work.
> 
> > Yes, for example yapf and clang-format both support it (via a --lines argument).
> 
> That option leaves some unanswered questions. Is it input or output line numbers? Does the program reformat entire files, then recover original lines based on the ranges? Or if formatting only happens for the nodes within the ranges, what happens if a node is cut in half?
Input lines (I guess it's hard to expect the user to know the output line numbers ahead of time).
Re the implementation details- I can try to answer, but frankly I don't have a strong need for this anyway, I'm just fulfilling a request I got in the PR :)
> 
> In other news, I don't see a simple way to implement this that will be straightforward to implement and maintain.

**Comment by mvdan** [comment]
> only the line range is sent to the formatting tool, ignoring the other context, but as you can expect that doesn't always work.

Thinking how I'd possibly implement this internally for a range of input lines, the limitations would be the same. So I don't see the point of such a feature. The syntax package only knows how to print nodes, so it can't print "half a node".

And that ties to why I was asking about input lines. We could possibly support a range of output lines, since we could simply format the entire file, and then just keep those lines. But one can accomplish this already from outside the tool, so I again don't see the point of the feature.

Perhaps I'm missing some magical algorithm that one can use to selectively format arbitrary lines easily. Or perhaps other formatters like clang-format are just very different from this one. But with the current design, I just don't see a way to support such a feature well.

Closing this for now, but happy to reopen if someone has an idea of how this is usually implemented.
