### ISSUE TITLE
space format

### ISSUE THREAD

**Issue by medifle** [mvdan/sh#343]
MacOS: 10.14.2
Bash: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

`shfmt` does not correct the following syntax error

```bash
#!/bin/bash
FILE = a_file.txt  # space should be removed
if [-f "$FILE" ]; then  # A space is needed before `-f`
	echo FILE exists
fi
```

which should be

```bash
#!/bin/bash
FILE=a_file.txt
if [ -f "$FILE" ]; then
	echo FILE exists
fi

```

Otherwise, the first case is going to raise an error:
![image](https://user-images.githubusercontent.com/13296643/50605470-5a070600-0e90-11e9-98ac-8b114ba0b918.png)

It would be better to correct the format to avoid such syntax errors

**Comment by mvdan** [comment]
Sorry, I don't understand the issue. What are you trying to do?

**Comment by medifle** [comment]
> Sorry, I don't understand the issue. What are you trying to do?

updated issue description

**Comment by mvdan** [comment]
These are not syntax errors. `foo = bar` is a valid command, syntactically. For example, try `echo = bar` versus `echo=bar`.

Similarly, `[-f foo ]` is a valid command syntactically, just like `[ -f foo ]` or `"[" "-f" "foo" "]"`. `[` is a builtin command, so these last two actually behave equally.

So `shfmt` can't possibly add spaces to "fix" the program's syntax because it simply isn't broken. The program evidently doesn't do what you wanted it to do, but that's because you wrote a different program to the one you intended.

`shfmt` is a tool to rewrite files to use a canonical format, not to fix common mistakes in programs. That's what linters and bug finding tools are for. You could fairly easily write a tool in Go using the [syntax](https://godoc.org/mvdan.cc/sh/syntax) package to fix common issues in programs, such as replacing `[-f foo ]` with `[ -f foo ]` and `foo = bar` with `foo=bar`, but that can't happen in a tool like `shfmt` because it serves a different purpose.

A tool that catches many of these "beginner mistakes" is [shellcheck](https://github.com/koalaman/shellcheck). Though it's a very different tool - as far as I know, it can't update files nor format them.
