### ISSUE TITLE
Allow arbitrary spaces before an inline comment

### ISSUE THREAD

**Issue by tterranigma** [mvdan/sh#371]
`shfmt` enforces a single space before an inline comment. This reduces readability, especially when no syntax coloring is used and when the comment contains commented out code. 

As an example of a standard that requires more than one space before an inline comment is PEP8.

`-kp` is not a sufficient solution as it will keep all vertical alignment.

I don't have any more arguments!

**Comment by mvdan** [comment]
> As an example of a standard that requires more than one space before an inline comment is PEP8.

This is a Python formatting standard though, not a Shell or Bash one. Can you cite any that is specific to shell?

> `-kp` is not a sufficient solution as it will keep all vertical alignment.

The reason for `-kp` is precisely to make all these users happy without adding 20 flags. There could be flags to control:

* comment spacing
* comment alignment
* opening braces and keywords
* position of redirect operators
* spacing of redirect operators
* ...

The path I decided for is to stick to a single format with a few flags for common needs, such as indentation. Some of the spacing needs are their own flags because the shell community is split on what is the most popular format. For example, see `-sr`.

However, I don't think spacing of comments is such a common issue. As far as I can see, most shell style guides out there, and most code out there, uses a single space. So for the few who want something else, they can either stick to our default, or use `-kp`. That's the tradeoff we're making.

**Comment by tterranigma** [comment]
> This is a Python formatting standard though

Yes, I just mentioned it as a standard that justifies indentation of inline comments. 

Of the bash standards I have looked into, only some deal with inline comments and of those, the requirement is to be consistent on alignment. I guess `-kp` covers this.
