### ISSUE TITLE
Integrity checking

### ISSUE THREAD

**Issue by cultavix** [mvdan/sh#394]
Hi,

Would it be possible for you to publish/release an integrity check of some kind? Like either md5, sha256sum, whatever you'd like... You could release it along with your semtag.tar.gz / zip files.

Would be of huge help, I can help you write the code if you'd like on TravisCI?

Thanks again!!

**Comment by mvdan** [comment]
You mean checksums of the published releases? If so, do you mean the built binaries, or the source code?

**Comment by mvdan** [comment]
I'm going to close this for now, since there wasn't a reply. If you want integrity checking, the simplest is going to be to pin to a specific git commit, and build. Building should only take a few seconds on decent computers.

Or, if you want to download a zip or binary, checksum that the first time you download it. If someone can compromise the downloads, they could just as easily compromise a checksum that I publish alongisde them.
