### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#405]

**Comment by mvdan** [comment]
Sorry, but no. Much like with #120, I need strong evidence that people write lots of scripts in the language. This is true for Bash and POSIX, but as far as I know zsh and fish are mainly interactive shells.

In other words, I have zero interest in using or writing this. The first step to making this possible would be for a developer to volunteer the hours to actually write a proof-of-concept, that we can then review and evaluate.

**Comment by mvdan** [comment]
No answer in a week - closing for now, as I won't be doing this myself.

**Comment by phatblat** [comment]
I write a lot of scripts in fish shell. I have [799 custom fish functions](https://github.com/phatblat/dotfiles/tree/master/.config/fish/functions) in my dotfiles and could sure use a tool like this to help with formatting. I'll take a look at what it would take to add support for fish shell.

**Comment by mvdan** [comment]
I imagine it would be a significant amount of work. Open an issue with an overview of the changes planned before you start writing code, because this kind of refactor is the kind of change that needs some thought before it can be pushed to master. Beware that we also need to worry about backwards compatibility - a v4 will likely happen in the future, but not before summer.
