### ISSUE TITLE
keep `;` at end of new-line separated lists

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#41]
I commonly do something like: 
```
foo \
bar \
baz \
another \
;
```

so that I can just add new entry/entries anywhere and then visually select and sort in vim. Unfortunately shfmt drops the final `\` and the `;` which then messes up my workflow when something new is sorted at the end. This is very likely a niche annoyance so I'd like to know your thoughts.

**Comment by mvdan** [comment]
This sounds fine to me because it doesn't affect users who don't do this, and it's akin to optional trailing commas in lists that many languages already support. I agree with you that such language/format features allow for simpler scripting and diffing.

If we add this, should it be consistent across all tokens that terminate a statement? Besides `;`, these are `&`, `&&`, `||`, `;;`. I don't think enclosing tokens like `)` should ever show this behaviour.

**Comment by mmlb** [comment]
I've never done anything but `;` so I wouldn't add the others until someone asks.

**Comment by mvdan** [comment]
Sounds fair. Will work on it soon.

**Comment by mmlb** [comment]
:toot: thanks

**Comment by mmlb** [comment]
thanks!
