### ISSUE TITLE
interp: api suggestions

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#414]
1. https://github.com/mvdan/sh/pull/415 `func(*Runner) error` should be `type RunnerOption func(*Runner) error` this makes godoc look much better (same goes for syntax.Parser).
2. `With*Modules` funcs shouldn't accept multiple funcs, it's up to user whether they want to map commands via slices, maps, radix trees, switch cases or others.
3. DONE ~~Assuming you change WithExecModules, `ExecBuiltin` becomes unnecessary as it can be easily implemented by user.~~
4. `DefaultExec` (and Open) should be constructor instead `func DefaultExec() ExecModule` this makes godoc look better.
5. I can't understand how `ModuleCtx.KillTimeout` field would be used by user. Needs an example or be removed.
6. https://github.com/mvdan/sh/pull/418 `ExecModule` is currently a type alias, I haven't seen it used in such a way before, the only user-visible change seem to be compiler error messages, it might make sense to change it to regular type to make it clear what specific named type needs to be implemented.
```
cannot use func literal (type func(context.Context, string, string) error) as type func(context.Context, string, []string) error in assignment
vs
cannot use func literal (type func(context.Context, string, string) error) as type interp.ExecModule in assignment
```
7. Runner uses both functional options and struct fields. Idea of functional options is to reduce complexity of dealing with default and optional configuration, but by exporting both you actually double that complexity. It's currently unclear what defaults `Env` and `Dir` has or can I modify `Vars` after `Run()`.
I suggest removing struct fields and instead add SetOption(opts ...InterpOption) method. If you want to expose internal interpreter data, make a `State() *state.InterpState` method.
8. `Reset()` needs better docs on how it interacts with `Env`, `Vars`, `Funcs` (for example if user set `Runner.Vars`, `Reset()` will unexpectedly clear it)
9. `expand.Config.CmdSubst` default is unclear (and it's nil) yet docs for expand.Fields suggest that it'll just work. It may be better to switch `expand.*` funcs to functional options and remove Config struct entirely.
10. Is `ModuleCtx.UnixPath()` useful? How do you get such a path? `filepath.IsAbs()` returns true for paths starting with /, so calling `filepath.Abs()` shouldn't prepend CWD to it `/dev/null`.
(I don't have a windows machine atm so cannot test it)
https://golang.org/src/path/filepath/path_windows.go#L52
11. With extension of `errors` package in go 1.13 comparison with error type becomes even more clunky than it was before. I suggest making 4 funcs instead `func ErrorExitStatus(code int) error` `func IsErrorExitStatus() (code int, ok bool)` and unexport both error types.
12. `runner.RunFile` and `runner.RunString` sugar would be nice.

**Comment by kaey** [comment]
> 6. Defaults for `Env` and `Dir` are unfortunate, I think people would want to use gosh in a clear environment by default (at least thats what I want)
Making `Env` inherit env explicitly is easy `interp.Env(expand.ListEnviron(os.Environ()))`. Dir is a bit harder, both CWD and / can be confusing defaults and `os.Getwd()` returns error, not sure whats the best way here.

exec.Command inherits both Env and Dir by default and doing the same here is fine. Suggestion removed.

> 12. `runner.RunFile` and `runner.RunString` sugar would be nice.

Added.

**Comment by mvdan** [comment]
Thanks for raising this issue. There's a lot to process here, so bear with me.

1 - You're probably right. I hadn't thought about godoc grouping the option constructors together. Want to send a PR?

2 - What's the harm in allowing multiple funcs? If a user doesn't want to use the layered list, that's fine, they can just use one argument. This is for the sake of simplicity; using two modules can be done in a single line without having to do anything fancy.

3 - I agree that `ExecBuiltin` isn't necessary, but the thought was that it could be useful for simple cases. Then again, it's only a few lines, so we might as well just stick those in an example.

4 - Most people shouldn't be paying attention to the default funcs, so I don't think this matters. Having the functions be a simple static function is a plus.

5 - It's a detail necessary to properly implement DefaultExec, so it had to be exposed. It should be documented though.

6 - The reason it's a type alias is so that one can do:

```
WithExecModule(func(args ...) { ... })

// and not have to explicitly use the named type:
WithExecModule(ExecModule(func(args ...) { ... }))
```

If you're convinced otherwise and can send a working patch, I'll gladly merge it.

7 - The fields exist so that they can be read; for example, to gather set variables after interpreting a script. To set them up before running a program, in general options should be used instead; I should document that better. I don't think a `State` method would make this better; if it copies it's expensive, and if it doesn't copy it's just an extra layer that I'm not sure helps.

8 - Yup.

9 - The default does *not* include arbitrary code execution on purpose. The `expand` package is a bit low-level, so it's up to the user to explicitly enable running arbitrary code. If that's unclear, please file an issue about writing an example.

10 - The point of `UnixPath` was to make handling paths a bit easier, as you wouldn't have to worry about backslashes. You're probably right that it's not very useful, though; we can remove it.

11 - Sorry, I don't follow what you mean. The same code that you could write before, you can still write it now.

12 - Maybe - but what signatures would they have? Would they take options? Would they have any different defaults? Also, they would probably belong in `shell`.

**Comment by kaey** [comment]
>4 - Most people shouldn't be paying attention to the default funcs, so I don't think this matters. Having the functions be a simple static function is a plus.

They can still be static, just unexported. The difference is that they will positioned under their corresponding type in godoc this way and not clutter top-level function list.

>11 - Sorry, I don't follow what you mean. The same code that you could write before, you can still write it now.

Now user can wrap errors with `fmt.Errorf("my shell script failed: %w", err)` user will have to change their checks from this
```
if err != nil {
    if code, ok := err.(interp.ShellExitStatus); !ok || code != 0 {
        t.Fatal(err)
    }
}
```
to this
```
if err != nil {
    var code *interp.ShellExitStatus
    if errors.As(err, &code) || code != 0 {
        t.Fatal(err)
    }
}
```
with my suggestion it changes to 
```
if err != nil {
    if code, ok := interp.IsErrShellExitStatus(err); !ok || code != 0 {
        t.Fatal(err)
    }
}

**Comment by kaey** [comment]
>8 - Yup.

Actually runner.Reset() tries to save user from re-initializing, but does so in a buggy way. I think it's better to just remove it for now. You can always readd it later when somebody asks for it.

**Comment by mvdan** [comment]
> The difference is that they will positioned under their corresponding type in godoc this way and not clutter top-level function list.

I think this is a deficiency of godoc, like I mentioned in a PR - so I'm not convinced that we should work around it here.

> will have to change their checks from this

They can keep their original code if it still works for them. If anyone is wrapping errors in between, using `errors.As` is the recommended way to handle that, so I'd rather not try to work around it. Unless there is an upstream recommendation to expose extra API to make `errors.As` a bit simpler to use?

> Actually runner.Reset() tries to save user from re-initializing, but does so in a buggy way. I think it's better to just remove it for now. You can always readd it later when somebody asks for it.

Can you clarify how it's buggy? I know of at least a few users depending on it today, so I'd rather not remove it. I think it's also generally useful; otherwise getting a clean interpreter would always mean throwing away the existing one (with its existing heap allocations) and creating a new one.

**Comment by kaey** [comment]
> 10 - The point of UnixPath was to make handling paths a bit easier, as you wouldn't have to worry about backslashes. You're probably right that it's not very useful, though; we can remove it.

>Edit: we can't remove it; it's necessary to implement OpenDevImpls, for example. If you run the tests under Windows, or Wine with GOOS=windows go test -exec=wine, you can see how they pass with UnixPath, but fail without it with confused paths.

It's a bit more difficult than this, on unix paths starting with `/` are absolute, on windows they are not.
```
echo a >/tmp/test
unix will write to /tmp/test
win will write to $CWD\tmp\test
```

I think the right fix here will be to pass paths as is to OpenModule without cleaning and let OpenModule clean them when needed.

**Comment by mvdan** [comment]
You know what - you're right :) The module already has the current directory, so it's not necessary at all for it to receive an absolute path to begin with. Will be making that change now.

**Comment by kaey** [comment]
>I think this is a deficiency of godoc, like I mentioned in a PR - so I'm not convinced that we should work around it here.

What you basically say is that godoc need to automatically assume that `func (*Parser)` == `ParserOption`.
I'm sure this is never going to happen.

One possible alternative for default funcs is to assign them to variables
`var DefaultOpen ModuleOpen = func blablabla`

**Comment by mvdan** [comment]
> I'm sure this is never going to happen.

I wouldn't be. The func in question is never grouped anywhere else, so there's no ambiguity. godoc is also getting some new features like https://github.com/golang/go/issues/25449 and https://github.com/golang/go/issues/25444, so the page should get easier to navigate over time.

> One possible alternative for default funcs is to assign them to variables

Does this make godoc any better? If so, I'll accept a PR :)

**Comment by mvdan** [comment]
This thread is getting too long and confusing with the dozen points; we've addressed about half of them, I think. If any others need further discussison or any action, please file separate issues. That's going to be much easier for me to keep track of what needs doing.

Once you've done that, we can close this.

**Comment by mvdan** [comment]
I've tackled a couple more minor suggestions. As said above, I'm closing this issue for now; please open separate issues if there's anything else we should do. Thanks again!
