### ISSUE TITLE
interp: Run should return nil error instead of ShellExitStatus(0)

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#417]
Calling `exit 0` or `exit $?` at the end of script is very common and currently requires users to handle it specially
```
if err != nil {
    if code, ok := err.(interp.ShellExitStatus); !ok || code != 0 {
        t.Fatal(err)
    }
}
```
There is no need for that.

**Comment by mvdan** [comment]
There is a need for that, actually; if you make that change, I'd hope that at least one test in `cmd/gosh` would start failing.

It uses `syntax.Interactive` to parse one statement at a time, and then runs each of those via `interp.Runner`.

If running one of those statements results in a nil error, nothing happens, and we continue.

If running one of those statements results in an `interp.ExitStatus` error, we usually just continue, but we report the exit status if that was the last/only statement being run.

If running one of those statements results in an `interp.ShellExitStatus` error, we must stop immediately and report the exit status. This includes `exit 0`; otherwise, running that command inside `gosh` would simply be a no-op.

I understand that getting this seemingly harmless error from `interp.Runner.Run` can be confusing. If so, perhaps the docs can be better. But the error needs to be there. Perhaps a future higher-level abstraction like `shell.RunString` could convert that into a nil error, because the error is generally only useful when running statements one at a time as part of a larger program or interactive session.

**Comment by mvdan** [comment]
Thinking out of the box a bit - since this is related to the `Runner` state, perhaps we could join `interp.ShellExitStatus` into `interp.ExitStatus`, and add a `func (*Runner) ExitedShell() bool` that reports whether the last statement ended with an `exit` command. This could work and make the API a bit nicer for the simple users, I think.

**Comment by kaey** [comment]
I see. `syntax` already has different logic for parsing scripts and running interactively, it makes sense to do the same for interp.Runner (maybe `interp.Interactive` option)

**Comment by andreynering** [comment]
Thanks for this guys!
