### ISSUE TITLE
interp (maybe others, too): Keep a change log

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#423]
Hi,

Change logs are a good way of informing users of which changes were made in the API and behavior of the package(s). It helps users to know about what they need to be aware when upgrading the library or tool, specially breaking changes (but also new stuff, fixed bugs, etc). It's an important source of information when hunting bugs. Ideally it should link to the relevant issues, PRs or commits.

I see [there's some logs in the releases page](https://github.com/mvdan/sh/releases), but sometimes people like to live dangerously and use the master branch. 😎

**Comment by kaey** [comment]
We definitely should write docs for upgrading v2->v3 and v3-alpha->latest.
Full changelog in text format would be nice, but I don't want to work on it.

**Comment by mvdan** [comment]
Thanks for filing this issue. I do keep changelogs for stable releases, which you can see for recent v2 tags.

v3 doesn't have a formal changelog yet because it's not ready. The fact that v3 hasn't been released yet is partly my fault; it's almost a year overdue at this point. So the changelog will be "yuge" :) It will definitely need to outline all the API breakages that came since v2.

I'm not sure that keeping a changelog for alpha releases and master is worth the effort. The alphas are simply points at which master worked well enough and had changed considerably since the last tag; they're not ready for users.

I will start working on a changelog though, and probably share it somehow such as google docs. That's perhaps enough for the few who are using the alphas, until the final release comes later this month.

**Comment by andreynering** [comment]
This issue is just an idea. Feel free to proceed as you prefer.

I'll be happy enough with an upgrade guide once v3 is released. 🙂

The idea of having change logs available in the master branch is indeed more helpful to power users to check what's coming and try edge. It's not strictly necessary.

**Comment by mvdan** [comment]
Have a look at the changelog above and let me know what you think.

It definitely doesn't cover "how to upgrade from v2 to v3", but I'm not sure if that's going to happen. If it was exhaustive, it would be a huge document that would take many hours to write, at which point I expect most users wouldn't bother reading it.

Most of the backwards-incompatible changes are renames, moves to a different package, or changes of types. Those should all be pretty straightforward to spot and fix. If anyone encounters issues, they are welcome to open an issue and I can give pointers.

**Comment by andreynering** [comment]
@mvdan Thanks!

The changelog is fine. And I agree that we don't need huge upgrading guide, just the enough for the basic usage, and people can jump into the changelog and docs if needed.

I'll let you know if I find any missing information in the changelog.
