### ISSUE TITLE
js package bug: new line escape character removed incorrectly

### ISSUE THREAD

**Issue by JounQin** [mvdan/sh#424]
Thanks very much for building this project, and I'm trying to wrap it into a [prettier](https://prettier.io) plugin: [prettier-plugin-sh](https://github.com/rx-ts/prettier/tree/master/packages/sh), it works well for most cases.

But I just find an issue when formatting `Dockerfile`:

```dockerfile
# input
FROM node:lts-alpine          as       builder

COPY        .      /app
WORKDIR         /app
RUN yarn           --frozen-lockfile &&            \
    yarn       build &&           \
    find . -name      '*.map' -type f -exec rm -f {} \;

FROM          abiosoft/caddy
COPY --from=builder          /app/packages/ufc-host-app/build /srv
EXPOSE      2015
```

```dockerfile
# output
FROM node:lts-alpine as builder

COPY . /app
WORKDIR /app
RUN yarn --frozen-lockfile &&
	yarn build &&
	find . -name '*.map' -type f -exec rm -f {} \;

FROM abiosoft/caddy
COPY --from=builder /app/dist /srv
EXPOSE 2015
```

It is clear the `\` character after `&&` should not be removed.

**Comment by kaey** [comment]
Do you try to run shfmt directly on Dockerfile? This is not supported as Dockerfile is not a shell file its syntax is different and it can break in other ways.

**Comment by mvdan** [comment]
What @kaey said. Removing the `\` is correct in shell, because a line ending in `&&` just continues the command in the following line.

You coudl potentially work around this by using `shfmt -bn`, which puts operators like `&&` on the next line, thus needing to add `\` before the newline. The printer has the same option. Though I imagine you'd easily run into other issues with Dockerfiles.

**Comment by JounQin** [comment]
> Do you try to run shfmt directly on Dockerfile? This is not supported as Dockerfile is not a shell file its syntax is different and it can break in other ways.

Then what's the difference between the JS API and `shfmt` itself? I've passed the `filapath` to `parser.Parse` function:
https://github.com/rx-ts/prettier/blob/master/packages/sh/src/index.ts#L17

**Comment by JounQin** [comment]
@mvdan I'm using the JS API, it there any related API to preserve new line as like as `KeepComments`: `syntax.KeepComments(parser, true)`?

**Comment by JounQin** [comment]
@mvdan How can I access functions like `BinaryNextLine` in the JS API? It seems they are not exported as public API?

**Comment by mvdan** [comment]
@kaey asked you to reproduce the issue with shfmt because that tool ends up running pretty much the same code to format shell code.

The JS package doesn't have printer options like BinaryNextLine right now. It probably will in the future, but again, this won't be enough to support dockerfiles. You're going to need a parser that understands dockerfiles.

**Comment by JounQin** [comment]
@mvdan `-bn` did the trick, really hope this feature in js package, is there anything I can offer help to achieve this?

Related: https://github.com/foxundermoon/vs-shell-format/issues/31
