### ISSUE TITLE
Bash syntax is fine but I get: $ cannot be followed by a word

### ISSUE THREAD

**Issue by Jeansen** [mvdan/sh#449]
I've got a big script (https://github.com/Jeansen/bcrm/blob/master/bcrm.sh) that has valid Bash syntax, but when running shfmt against it I get: `$ cannot be followed by a word`.

That happens only in two cases: Here are the excerpts:

https://github.com/Jeansen/bcrm/blob/2a1cf0cf13cd7081d40f5bc8b34ff0282cd25152/bcrm.sh#L1691
```
[[ -n $DEST_IMG ]] && mount_ "${DEST_IMG%/*}" -p "$SCHROOT_HOME/${DEST_IMG%/*}" -b
[[ -n $SRC_IMG ]] && mount_ "${$SRC_IMG%/*}" -p "$SCHROOT_HOME/${$SRC_IMG%/*}" -b
```
Commenting out the second line resolves the issue, but there is another one a bit later in my script:

https://github.com/Jeansen/bcrm/blob/2a1cf0cf13cd7081d40f5bc8b34ff0282cd25152/bcrm.sh#L1717
```
umount_ "$SCHROOT_HOME/${$SRC_IMG%/*}"
umount_ "$SCHROOT_HOME/${DEST_IMG%/*}"
```
Commenting out the first line resolves the issue and then I can run shfmt just fine.

**Comment by mvdan** [comment]
Hm, are you sure that's valid syntax?

```
$ echo "${$SRC_IMG%/*}"
bash: ${$SRC_IMG%/*}: bad substitution
```

Nothing changes if I try `SRC_IMG=whatever` first, so the value is not related.

I think your syntax is indeed invalid; you probably want `${SRC_IMG%/*}` without the duplicate dollar sign. Note that if bash doesn't give you an error sometimes, it's because it only evaluates substitutions when a command is run; they're not all parsed statically. On the other hand, this parser does all parsing upfront.

**Comment by Jeansen** [comment]
Hm..yes. you are right. Though I wonder why bash does not complain here when using -n. But that might exactly be the case because it is a local function an not called. I'll close it. And thanks for your quick reply! :smile:

**Comment by mvdan** [comment]
Yup, `bash -n` is equally lazy. This is partly due to the language design, but it also makes detecting syntax errors a nightmare in shell :) At least, unless you use a static parser like this one.

**Comment by Jeansen** [comment]
Yes, that's true. I am therefore extremely happy you maintain this project.
