### ISSUE TITLE
interp: panic: unhandled word part: *syntax.ProcSubst

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#451]
Hi,

I think this error is probably by design for a syntax not yet implemented. Opening this issue anyway to have a confirmation and know if you plan to implement it in the future.

Initially reported here: https://github.com/go-task/task/issues/270

Reproduced by running the following command on both `v3.0.0-alpha3` and `v3.0.0-beta1`:

```bash
grep -m 1 "Started EhrBase in" <(tail -f log)
```

**Comment by mvdan** [comment]
Yup, just a classic case of being lazy :) A patch is welcome, if anyone wishes to work on this.

**Comment by andreynering** [comment]
Hi @mvdan,

Thanks for addressing this!

Wasn't this released yet? I don't see this fix on the CHANGELOG, neither this seem to work for me after upgrading to v3.0.1. I still get:

```go
panic: unhandled word part: *syntax.ProcSubst
```

**Comment by mvdan** [comment]
This is milestoned for 3.1.0; yesterday's release was the 3.0.1 bugfix release.

I didn't backport this, nor #447, because both are non-trivial features.

3.1.0 will probably come out in a few weeks. If you want the feature sooner, just pin master; there are extensive tests that are periodically run on all three platforms, so it should be pretty safe to use specific master versions.

**Comment by andreynering** [comment]
Oh, I got it. No problem and thanks!
