### ISSUE TITLE
alias and unalias panic

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#456]
`interp.Runner.builtinCode` [panics](https://github.com/mvdan/sh/blob/b40688c926753d9a42176476d58afea69b0ecb09/interp/builtin.go#L565) on `alias` and `unalias` (among other things).

Any support planned for these?  Any suggestions if not?  PRs welcome?

**Comment by mvdan** [comment]
These are indeed TODOs; the larger issue is https://github.com/mvdan/sh/issues/97, though I wonder why the link there doesn't list `alias` and `unalias`.

A PR is welcome if you'd like to work on it. It should be pretty straightforward, as long as we add enough test cases for the possible scenarios where aliases are meant to work or be ignored. Otherwise we can leave this issue open as "help wanted".

**Comment by theclapp** [comment]
FWIW, the [bash manpage](https://manned.org/bash.1#head16) says "The rules concerning the definition and use of aliases are somewhat confusing. [... A paragraph of somewhat confusing rules ...]  For almost every purpose, aliases are superseded by shell functions."  And you support `function`.  So I'll just use that for now.  Thanks.

**Comment by mvdan** [comment]
Yep, aliases are kind of weird. I only really use them for tiny interactive things :)
