### ISSUE TITLE
syntax: KeepPadding should obey extra indentation when indenting with spaces

### ISSUE THREAD

**Issue by oliv3r** [mvdan/sh#471]
We currently have the option to choose between indentation format, tabs vs spaces. However, it is very common (when using tabs) to only use tabs for indentation, but use spaces to align.

The most obvious spot is when aligning multiple if terms on multiple lines.

To give an example.
```console
	image="some long string" \
	      "spanning multiple lines"

	if [ -n "${image}" ] && \
	   docker build \
	          --hostname "$(hostname)"
	          --rm \
	          --interactive \
	          --tty \
	          --workdir "${workdir}" \
	          "${image}" "$(pwd)"; then
	fi
```
(note that github doesn't use a monospace font for rendered code, but not when editing/entering text *sigh*)
Here we have one indentation level (the level of the if) and alignment of the arguments.

The reason why we want to do this, is that regardless of the tabstop setting, things are always properly aligned. Using spaces only fixes this of course, but tab users don't want to ;)

I tried using -kp but that only messes with the arguments (hostname and workdir) and aligns those.

When [searching](https://duckduckgo.com/html?q=tab%20to%20indent%2C%20space%20to%20align) for it we get plenty of results.

I think vim calls it [smart-tabs](https://vim.fandom.com/wiki/Indent_with_tabs,_align_with_spaces#Smart_tabs)?

Since you probably don't want a new option for this, this would either be needed to be auto-detected (how to know when a space is for alignment vs just a stray whitespace following an indentation tab) or -i could be changed from uint to sint and -1 would be tabs with alignment :) This would 'break' if a user insist on having INT_MAX + 1 - UINT_MAX number of spaces, but since having anything more then 128 spaces shouldn't even be considered I think we're good.

**Comment by mvdan** [comment]
People mix tabs and spaces for indentation? This is making my skin crawl :P

> Using spaces only fixes this of course, but tab users don't want to ;)

`shfmt` doesn't have to accomodate every user, and that's okay. As a general rule of thumb, I'll only add formatting options for stuff that's encouraged/enforced in relevant formatting styles, or very popular, e.g. used in at least a quarter of the shell code out there by some approximation.

This request doesn't seem to fall under either as far as I've seen in many years, at least as far as shell code. And I personally have zero incentive to write the code or maintain it, especially since it sounds like it would be a fun source of headaches.

We could discuss something like this for space indentation if you'd like, perhaps as an extension to `-kp`. But it's unlikely I'll be convinced to accept this as is.

**Comment by oliv3r** [comment]
Hmm, your response surprises me, as editors actually have built-in support for smart-tabs.

Vim has a plugin, intelj it's built in an an option VSCode has a plugin for it, QTCreator does it with a built in also.

The reason is simple, you want to have consistent alignment, regardless of the tabstop size. It is far more common then you'd think :) I guess since a lot of shell-scripts are space aligned, you probably don't see it very often.

but are you arguing you do your if statements as such?
```sh
	if [ true ] && \
	[ false] && \
	[ true ]; then
		echo "Hello"
	fi
```

or
```sh
	if [ true ] && \
		[ false] && \
		[ true ]; then
		echo "Hello"
	fi
```

you have to admit, both look strange :p let alone when rendering them with different tabstops (and different keywords, as a tabstop of 3 spaces would work-ish here)

**Comment by mvdan** [comment]
I do the latter. It's what some tab-based languages like Go do. You get used to it after a while.

Note that I have nothing against "perfect alignment" with space indentation, per se. I don't like using it, but I don't have anything against those who enforce it. And, like I said before, I don't have anything against obeying the user's choice for "indentation alignment" in `-kp` when spaces are used to indent. It would just be another way to obey the user's preference for extra padding.

What I argue we definitely don't want to do is:

* Mixing spaces and tabs, because I see no reason to do it, and because it would complicate the job for `-kp`. For example, how long is a tab? We'd need an extra option for that.
* Auto-detect "smart tabs". That sounds like a heuristic approach that would require a fair bit of code and tests, and a bunch of headaches in the long run.

**Comment by mvdan** [comment]
> Hmm, your response surprises me, as editors actually have built-in support for smart-tabs.

I'm curious if you have links, by the way. As far as I can tell, vim requires installing a plugin to obtain "perfect alignment" while using tabs exclusively for indentation.

Editors having support for this out of the box is certainly an indicator of popularity, but not necessarily with shell code. Our tool is also far from an editor; it's not uncommon for editors to have hundreds of options.

**Comment by oliv3r** [comment]
Maybe I don't follow then, as -kp doesn't work and actually makes it worse :)
```diff
 docker_run()
{
 	if [ "${src_name#docker_}" != "${src_name}" ]; then
 		_argv0="./${src_name#docker_}"
 	else
 		usage
 		_argv0="/bin/sh"
 		echo "Starting shell inside container"
 	fi
 
 	eval docker run \
-	            --rm \
-	            --hostname "$(hostname)" \
-	            --interactive \
-	            --tty \
-	            --workdir "${WORKDIR}" \
-	            "${opt_docker_args:-}" \
-	            "${CI_REGISTRY_IMAGE}" \
-	            "${_argv0:-}" "${@}"
+		--rm \
+		--hostname          "$(hostname)" \
+		--interactive \
+		--tty \
+		--workdir          "${WORKDIR}" \
+		"${opt_docker_args:-}" \
+		"${CI_REGISTRY_IMAGE}" \
+		"${_argv0:-}"          "${@}"
 }
```

Here is what it currently does

**Comment by mvdan** [comment]
Yes - I propose that, as an alternative, and when using space indentation, `-kp` could be made to obey this kind of extra indentation for the purpose of alignment.

**Comment by oliv3r** [comment]
the only downside would be that -kp would randomly align (in this case) function arguments. But it would be a big win already :) this would atleast work for the 'if' problem, where you align multiple if components with the opening braces

**Comment by mvdan** [comment]
Hm, I wouldn't call it "random". `-kp` is just about obeying whatever spacing/padding choices the user made. If the user made specific "perfect alignment" choices, it shouldn't break.

If this sounds like a good idea, I'm happy to retitle the issue and see if someone is interested in doing the work. I have no plans to do it myself in the short term.

**Comment by mvdan** [comment]
@oliv3r just to clarify, are you OK with the above? If not, I don't see another way we could tackle this feature request.

**Comment by oliv3r** [comment]
Sorry for not answering in time, but that sounds like a good plan. I think we can get the -kp flag to play along just right. Not sure what you had in mind with re-titling it; but lets do it :)

**Comment by maximbaz** [comment]
> You basically want to change this:
> 
> https://github.com/mvdan/sh/blob/3a030eb308a30d0dccffbed287b65ab1df0f1cc2/syntax/printer.go#L271-L276

I think that isn't the case, if I make a simple change to add `p.WriteByte(' ')` inside that `if`, it will only affect the first line, like so:

```
  source=('one'
    'two'
    'three')
```

I think `elemJoin()` never really calls `spacePad` for its elements, it does however call

https://github.com/mvdan/sh/blob/3a030eb308a30d0dccffbed287b65ab1df0f1cc2/syntax/printer.go#L875

which in turn calls 

https://github.com/mvdan/sh/blob/3a030eb308a30d0dccffbed287b65ab1df0f1cc2/syntax/printer.go#L466

which finally just adds spaces like so:

https://github.com/mvdan/sh/blob/3a030eb308a30d0dccffbed287b65ab1df0f1cc2/syntax/printer.go#L378-L379

Good news: at this point we know that we are indenting with spaces (there is a `case` for tabs just above). 

But what confuses me is how to access the previous line here, in order to change the math of calculating number of spaces. And would that even be possible? When rendering `'two'`, I need now only the previous line, but actually the position of the opening quote of `'one'` on the previous line...

Am I unnecessarily complicating this too much? 😄

**Comment by mvdan** [comment]
> Am I unnecessarily complicating this too much?

A little bit - you really don't care about the first line, you just care about the word you're currently printing. `-kp` is just about keeping existing padding. If you are formatting a word that was at column 10 and you indent with 4 spaces for a single indentation level, then `spacePad` should add six spaces to keep the original vertical position.

So `-kp` is not about aligning your array elements. You do the alignment however you want - there are lots of ways to do them - and `-kp` just lets you do your thing without intervening.

I suspect you might need to make `elemJoin` call `spacePad` somewhere, I haven't looked.

**Comment by maximbaz** [comment]
Oh, I think I understand what you are saying... So with a patch like below, we basically allow users to align even the beginning of the lines, as long as they use `-kp` and space indentation. This definitely works for my example, I just didn't expect the full scope of the change. 

I didn't add the tests, but on a first glance, does this look correct to you, is this what you had in mind?

```diff
--- a/syntax/printer.go
+++ b/syntax/printer.go
@@ -269,17 +269,14 @@ func (p *Printer) space() {
 }
 
 func (p *Printer) spacePad(pos Pos) {
-	if p.cols.lineStart {
-		// Never add padding at the start of a line, since this may
-		// result in broken indentation or mixing of spaces and tabs.
-		return
-	}
-	if p.wantSpace {
-		p.WriteByte(' ')
-		p.wantSpace = false
-	}
-	for !p.cols.lineStart && p.cols.column > 0 && p.cols.column < int(pos.col) {
-		p.WriteByte(' ')
+	if !p.cols.lineStart || p.keepPadding && p.indentSpaces != 0 {
+		if p.wantSpace {
+			p.WriteByte(' ')
+			p.wantSpace = false
+		}
+		for p.cols.column > 0 && p.cols.column < int(pos.col) {
+			p.WriteByte(' ')
+		}
 	}
 }
 
@@ -873,6 +876,7 @@ func (p *Printer) elemJoin(elems []*ArrayElem, last []Comment) {
 		}
 		if el.Pos().Line() > p.line {
 			p.newlines(el.Pos())
+			p.spacePad(el.Pos())
 		} else if p.wantSpace {
 			p.space()
 		}
```

**Comment by mvdan** [comment]
Yep, that looks about right. I'd just keep the early return in spacePad, just to keep the logic easier to follow.
