### ISSUE TITLE
Add an explaination of why space are removed after a redirect

### ISSUE THREAD

**Issue by soullivaneuh** [mvdan/sh#475]
Even if we can change this with an option, it would be great to know why you decide to remove any space between the redirect and the target, like you did for caveats: https://github.com/mvdan/sh#caveats

A short explanation and/or a link on the input would be enough.

This might help people to decide what is the best for them.

**Comment by mvdan** [comment]
Hm, maybe. I don't want to make the README much longer by explaining the decisions behind every default. The defaults are, really, just arbitrary decisions based on some factors. The important part is that they are consistent.

I'll think about it and play with some changes to the caveats section.

**Comment by mvdan** [comment]
I thought about this some more. The caveats section is about things we absolutely can't support because of very steep tradeoffs. I don't think I want to document default formatting choices there.

As for documenting why the default format is the way it is: I'll add a short section to the man page. I'm not going to explain every single decision, because that would take two pages, and some of the decisions were arbitrary. What matters is that they're made and consistent for all shfmt users.
