### ISSUE TITLE
interp: Windows' network paths (\\MACHINE\foo\bar) are converted to C:\foo\bar

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#527]
Hey there,

Someone reported the mentioned issue on the Task project: https://github.com/go-task/task/issues/308.

Since I'm away from any Windows machine at the moment, I didn't try to reproduce it yet, but I think the bug is clear enough to be worth posting here already. 🙂

**Comment by kaey** [comment]
DefaultOpen only does `filepath.Abs`. Are you sure yaml correctly passes `\\` and `\f`?

**Comment by mvdan** [comment]
Yeah, it would be more helpful if this issue included a minimal reproducer with a tiny Go program, e.g. on the playground.

**Comment by andreynering** [comment]
Seems that the interpreter removes extra backslashes:

https://play.golang.org/p/DR8QY_PacbV

The same doesn't seem to happen with forward slashes:

https://play.golang.org/p/OVLNl6ayoyj

I asked the user to try if that works.

**Comment by mvdan** [comment]
Well, yes, that's the parser doing its job. In `cat "\\MYMACHINE\src\foo\bar"`, backslashes escape characters within double quotes:

```
$ echo $0
/bin/bash
$ printf "%s\n" "\\MYMACHINE\src\foo\bar"
\MYMACHINE\src\foo\bar
```

To write Windows paths on POSIX shell, use single quotes (which don't interpret backslashes), or always use double-backslashes for every single backslash you want in your string:

```
$ printf "%s\n" '\\MYMACHINE\src\foo\bar'
\\MYMACHINE\src\foo\bar
$ printf "%s\n" "\\\\MYMACHINE\\src\\foo\\bar"
\\MYMACHINE\src\foo\bar
```

The only reason this might be confusing to your users is because backslashes within double quotes aren't always treated the same. From https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02_03:

> The <backslash> shall retain its special meaning as an escape character (see Escape Character (Backslash)) only when followed by one of the following characters when considered special:
> $   `   "   \   <newline>

So if this is the cause of the problem your user was seeing, I don't think there's anything to fix on our side. On your end, I guess you could make task print a warning when running on windows and using double-quoted strings that seem to contain windows paths.

**Comment by andreynering** [comment]
Hi @mvdan,

The user said that using forward slashes works.

Feel free to close this issue if you don't plan to support backslashes for this use case.

**Comment by mvdan** [comment]
Yes, this is all working as intended as far as I can tell. Backslashes are interpreted the same for all platforms. It would be weird if we handled them differently on Windows.
