### ISSUE TITLE
cmd/gosh: forget history position

### ISSUE THREAD

**Issue by muv1** [mvdan/sh#550]
Currently I using Bash with Cygwin. With Bash, I can enter these commands:

~~~
$ date
Thu, Apr 23, 2020  7:51:43 PM

$ echo Sunday
Sunday
~~~

Then if I press Up twice, I get this, as expected:

~~~
$ date
~~~

If I want to cancel, I can press down twice, or Ctrl + C. After I have canceled,
if I press Up again, it gives me the most recent result, as expected:

~~~
$ echo Sunday
~~~

Now contrast with Windows Gosh. I can enter these commands:

~~~
$ echo Sunday
Sunday
$ echo Monday
Monday
~~~

Then if I press Up twice, I get this, as expected:

~~~
$ echo Sunday
~~~

but if I want to cancel, I cant press down twice. It only lets you press down
once, so that the most recent command displays:

~~~
$ echo Monday
~~~

as a workaround, you can press Esc. But then if you press Up, you dont get the
most recent result anymore. Because it didnt let you scroll all the way down,
you get this:

~~~
$ echo Sunday
~~~

I dont want the shell trying to be smart, and remembering the position in the
history. Does Gosh have some option to change this behavior?

**Comment by mvdan** [comment]
Hm. Exactly what version of `gosh` are you running? I'm pretty sure the tool has never supported any "readline-like" features, like history, or going up or down through the history. If I enter a command and press "up", I simply get `$ ^[[A` in my prompt, because the program doesn't interpret it in any way.

This is on master, via `go install ./cmd/gosh` and then running `gosh`. If you want to be sure you're running that program, you can also do `go build ./cmd/gosh` and then run `./gosh`.

**Comment by mvdan** [comment]
Also, to give a bit more context - the shell is mainly meant for experimentation and debugging purposes, and not as a full interactive shell to replace `sh` or `bash`. So, while adding history could be a good idea, all of those interactive features aren't really a priority.

**Comment by muv1** [comment]
I will just close then, as history seems to be something that isnt supported, and might not ever be supported. Thanks!

**Comment by mvdan** [comment]
To clarify: the syntax parser and the shell interpreter are intended for real use, even replacing bash entirely, but the `gosh` program is not meant to replace a full interactive shell.
