### ISSUE TITLE
syntax: -kp adds space padding right after tab indentation

### ISSUE THREAD

**Issue by greymd** [mvdan/sh#559]
First of all, thank you for creating and maintaining`shfmt`.
This is incredible tool!

Let me report some behavior that bothered me a bit.
`-kp` option breaks format of the script if the script has multiple commands separated by semicolons in `{...}` ([Grouping Commands](https://www.gnu.org/software/bash/manual/html_node/Command-Grouping.html)).

Here is how I reproduce.

```
$ shfmt --version
v3.1.0

$ cat test.sh
echo 1 2 | { read a b; echo "$a";}

$ shfmt -kp -d test.sh
```

Result is like this.

```diff
--- test.sh.orig
+++ test.sh
@@ -1,2 +1,5 @@
-echo 1 2 | { read a b; echo "$a";}
+echo 1 2 | {
+                 read a b
+                           echo "$a"
+}
```

**Comment by mvdan** [comment]
`shfmt` forces command lists with more than one element to be on multiple lines, so this is why it's expanding that one line into four.

Since `-kp` is used at the same time, it then tries to keep the original horizontal position of each of those two commands. It only counts bytes, so it thinks a tab carries the same weight as a space. Hence why they get indented so much.

I think the right solution here is to never let `-kp` add padding right after indentation. Not only will that do weird things most of the time (like what you're seeing here), but it would also result in mixing spaces and tabs, which is horrendous.

**Comment by mvdan** [comment]
Ah, we were already doing that, but there was a bug, of course. Fix incoming.
