### ISSUE TITLE
syntax: dollar-quote strings aren't valid POSIX

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#563]
ShellCheck notes:

> SC2039: In POSIX sh, $'..' is undefined.

Looks like dollar locale strings (single or double quoted) aren't actually POSIX. Could mvdan/sh update the string expression parser accordingly?

I enjoy using mvdan/sh as a very strict parser, in order to catch more bashisms and such. On the whole, mvdan/sh does a great job at identifying different parts of my scripts that are not POSIX compliant.

**Comment by mvdan** [comment]
You're right, `$'` and `$"` are not specified in https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html.

I think I was confused because some POSIX shells like `busybox ash` do seem to support `$'`.

**Comment by mvdan** [comment]
Oh. We already do this:

```
        {                                
                Strs:  []string{`$''`},                           
                bsmk:  sglDQuoted(""),  
                posix: word(lit("$"), sglQuoted("")),
        },                                                 
```

Unfortunately for you, `$''` is valid in POSIX Shell too, it just does something different:

```
$ bash <<EOF
> echo $'a'
> EOF
a
$ dash <<EOF
> echo $'a'
> EOF
$a                              
```

So I don't think there's anything to fix here. `shfmt` can't complain because the input is valid POSIX shell too. If you want a tool that does extra checks like "this looks like a bashism", I think that should be a separate tool.
