### ISSUE TITLE
Using variable as arithmetic operator

### ISSUE THREAD

**Issue by aureliojargas** [mvdan/sh#583]
Maybe can this case be supported?

```console
$ cat op.sh 
#!/bin/sh
op='+'
echo "$((1 $op 2))"

$ bash op.sh 
3
$ shfmt op.sh 
op.sh:3:12: not a valid arithmetic operator: $
$
```

I already saw in some other issues here that the bash arithmetic syntax is a can of worms. I'm ok in getting a "no" as an answer :)

**Comment by aureliojargas** [comment]
From my side, I refactored my code to not use the arithmetic operator as a variable. Since this is not an issue for me anymore, I'm closing this one. Feel free to reopen if you think it's relevant anyway.

**Comment by mvdan** [comment]
We could potentially support this, but only in the form of `((x "$op" y))`. Otherwise, `op='foo bar'; ((x $op y))` would need to expand to `((x foo bar y))`, and our parsing of `$op` as a single operator would be wrong.

It also makes the arithmetic syntax tree far less useful if one can't know what the operators are. This is made worse by how arithmetic expressions can assign variables; it could be impossible to expand all operators upfront.

So yeah, I would prefer not to do this :) Bash allows for lots of trickery and magic, but we have to draw a line somewhere if we want to have a static parser.

**Comment by Montana** [comment]
Hi @mvdan, 

What are the trade-offs between supporting dynamic operator expansion in arithmetic expressions and maintaining a robust static parser? Are there any alternative approaches that could provide similar flexibility without compromising the integrity of the syntax tree?
