### ISSUE TITLE
syntax: KeepPadding should adjust relatively to the other changes made on the same line

### ISSUE THREAD

**Issue by maximbaz** [mvdan/sh#595]
I think the behavior of `-kp` is really not intuitive when `shfmt` makes other changes on the same line, and in some cases creates additional padding instead of keeping what user intended.

Take this simple example:

```sh
greet () {
  echo "hello world"
}
```

Running `shfmt` will move `()` to the left, but it will not move `{` with it, resulting in two spaces like so:

```sh
greet()  {
  echo "hello world"
}
```

Or take [this example](https://github.com/mvdan/sh/issues/471#issuecomment-572428985), prior to #594 it would change

```sh
eval docker run \
            --rm \
            --hostname "$(hostname)" \
            --interactive \
            --tty \
            --workdir "${WORKDIR}" \
            "${opt_docker_args:-}" \
            "${CI_REGISTRY_IMAGE}" \
            "${_argv0:-}" "${@}"
```

To:

```sh
eval docker run \
    --rm \
    --hostname         "$(hostname)" \
    --interactive \
    --tty \
    --workdir         "${WORKDIR}" \
    "${opt_docker_args:-}" \
    "${CI_REGISTRY_IMAGE}" \
    "${_argv0:-}"         "${@}"
```

I know that this particular example won't matter after #594, but the first example shows that the issue in general is still relevant.

I remember when I first time saw this behavior, I was really confused, and the author of the example above is certainly confused too.

So my proposal is to make `-kp` respect other changes that `shfmt` made on the line, if it moved `--hostname` by `8` columns to the left, `"$(hostname)" \` should also be moved to the left by 8 columns.

What do you think, would you agree with this statement?

**Comment by mvdan** [comment]
I have mixed feelings about this; initially, I too wanted `-kp` to do this. After all, the flag is called "keep padding" which seems to imply that it keeps the relative spacing between tokens, not the absolute column position of a token.

The problem comes with custom vertical alignments. If we simply obey the original column position, whatever vertical alignment the user had set up (e.g. aligned arguments, or comments, etc) will remain in place, because we won't move them.

If we suddenly start "shifting" those depending on how we changed the line up to that vertical point, then it's possible we'll break the vertical alignment.

I think both methods have their merits. It depends on whether the code was using absolute positions (e.g. vertically aligned arguments or array elements), or not. If the code was using absolute positions, the current method will be better. Otherwise, your idea would do better. The question is - how often does each show up in practice?

I really don't have a strong opinion here, because I personally don't use `-kp` :) If you're not sure either, we could leave this open as `help wanted` for a couple of weeks to see if others have an opinion.

**Comment by maximbaz** [comment]
I would like to explore this alternative option, to try using it locally and see how it goes, because so far the current method does confuse me from time to time, so it _feels_ the alternative method would be better 🙂 

Could you please give me some hints where to look at in the code to implement the "relative spacing"?

**Comment by mvdan** [comment]
After much thought over a number of years, I'm considering removing this feature in the next major release. See https://github.com/mvdan/sh/issues/658, and please try to keep an open mind when considering the benefits and drawbacks of the flag. Thanks!

**Comment by maximbaz** [comment]
Fair enough, you mention some very good points - I have disabled `-kp` option locally and will report in that thread if I spot something formatted in a clearly worse way 👍
