### ISSUE TITLE
parse: don't reject function names that contain hyphens

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#6]
$ cat x.bash
    f-hyphen() {
    	echo "hyphen"
    }
    f-hyphen
    $ bash x.bash
    hyphen
    $ shfmt x.bash
    x.bash:1:1: invalid func name: f-hyphen

**Comment by mvdan** [comment]
This was done on purpose since this is a POSIX restriction. I will not implement any Bash features that break POSIX compliance, such as:

```sh
(cat <<EOF
foo
EOF)
```

The above works in `bash`, but not `ash` or `dash`.

On the other hand though, we can allow this without breaking any POSIX programs. So it's a pretty unintrusive change. I'll do it.

**Comment by ebfe** [comment]
Thanks.
