### ISSUE TITLE
syntax: printer options aren't obeyed inside tab-indented heredocs

### ISSUE THREAD

**Issue by mikeBashStuff** [mvdan/sh#601]
```
+ ./shfmt_v3.1.2_linux_amd64 -i 0 -bn -ci -ln bash -d -sr ./t
--- ./t.orig
+++ ./t
@@ -1,8 +1,8 @@
 #!/bin/bash

 file=foobar
-echo $(<"$file")
+echo $(< "$file")
 cat <<- FILE
-       $(< "$file")
+       $(<"$file")
 FILE
```

I would expect `shfmt` to correct only the `+echo $(< "$file")` but leave the contents of the heredoc untouched, considering that `-sr` is in use. Am I missing something here? :)

**Comment by mvdan** [comment]
Thank you, this is indeed a bug :) 

The problem is that we use a nested printer for `<<-` tab-indented heredocs, so that we can add tab indentation as a post-process step. But as you can see in the code below, we completely forget to keep the options like `-sr`:

https://github.com/mvdan/sh/blob/master/syntax/printer.go#L419-L423

I'd be happy to review a PR; you could fix this for all options, and add a few tests in printer_test.go.

**Comment by mvdan** [comment]
@mikeBashStuff this should be a pretty simple fix, if you'd like to contribute :) If you would rather not, I'll fix it myself over the weekend.
