### ISSUE TITLE
Any way to ignore formatting lines?

### ISSUE THREAD

**Issue by JounQin** [mvdan/sh#602]
```sh
#!/usr/bin/env bash

# how to ignore formatting next line
die() { echo "$*" 1>&2 ; exit 1; }
```

Related https://github.com/rx-ts/prettier/issues/96

**Comment by mvdan** [comment]
I would rather not add support for such "magic" comments. Having said that, you have multiple options.

First, https://github.com/mvdan/sh/issues/564 should solve this particular case, because of the exit command.

Second, I will very likely reopen https://github.com/mvdan/sh/issues/333 soon, to add support for formatting line ranges. So if you have lines 1-10 and you want to format all except line 4, you could format the ranges 1-3 and 5-10.

**Comment by JounQin** [comment]
Hmm... Line ranges seem much more difficult to use than ignore comments between files and code changes.

> I would rather not add support for such "magic" comments.

I'm wondering why this is not preferred. AFAIK, a lot of linters/formatters support ignore comments such as clang-format, ESLint, prettier, stylelint, etc.

**Comment by mvdan** [comment]
Line ranges are perhaps harder to use, but I would rather not have two ways to accomplish very similar goals. Line ranges are also more powerful; they can be used without inserting comments in the source, and they are often used by editor integrations.

> a lot of linters/formatters support ignore comments such as clang-format, ESLint, prettier, stylelint, etc.

You mostly mentioned linters, which tend to have false positives by nature. A formatter shouldn't, because you should generally never have non-formatted code.

It's true that some other formatters have lots of options and extra features, but I don't consider that a goal :)

**Comment by mvdan** [comment]
I should also note that you could implement this with a bit of code wrapping shfmt. For example:

1) Read the input shell line by line, finding special comments like `#do-not-format` or whatever suits you
2) Convert those lines to line range flags for shfmt (note that this flag isn't implemented just yet)
3) Run shfmt

**Comment by mvdan** [comment]
I assume the replies above answered your question. I still think that adding more ways to use the same feature is not a good idea.

**Comment by JounQin** [comment]
> I assume the replies above answered your question. I still think that adding more ways to use the same feature is not a good idea.

I understand how to implement It based on your solution, but I also still think a built-in comment based support is better.

Anyway, I'm going to try to implement this feature based on current solution. 🍺

**Comment by mvdan** [comment]
If the formatter has a bug, please file it and we can get it fixed. The user could always skip using the formatter on the file for a few days/weeks until it's fixed, or live with the bug for that period of time.

**Comment by JounQin** [comment]
> If the formatter has a bug, please file it and we can get it fixed. The user could always skip using the formatter on the file for a few days/weeks until it's fixed, or live with the bug for that period of time.

It needs time to be fixed. 😅 Ignoring the whole file is bad then ignore a single line.
