### ISSUE TITLE
syntax: permit simple commands like `x[0]`

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#604]
I'm using the npm module `mvdan-sh@0.5.0`.

Your parser permits simple commands `x.y` or `x.y.z`, which I interpret as deep paths into js objects.
But commands like `x[0]` and `x[0].y` throw  `"a[b]" must be followed by =`, despite bash v5 allowing them.

Could this syntax be permitted?

---

_Clarification_: this syntax is permitted via `syntax.NewParser(syntax.Variant(syntax.LangPOSIX))`. However, I still want bash parsing features such as `CStyleLoop` and `DeclClause`.

**Comment by mvdan** [comment]
I think this is a fair request, but it's hard to implement. When we see the `[`, we start parsing an arithmetic expression. If the `=` is missing, we would then have to backtrack to re-parse the expression as a literal instead.

It might seem fine to backtrack, but it opens a can of worms. What if the input was `a[`, then a million spaces, then `0] `? Would we keep a million bytes buffered in memory? Would there be a limit? What would the limit be, and would that be compatible with Bash?

https://github.com/mvdan/sh#caveats covers this exact same problem with `${a[expr}` and `$((`; both require backtracking to parse in Bash, because they are both ambiguous to parse.

I'm not completely rejecting support for backtracking, but it's a tricky feature to add, and needs careful thought. On the other hand, not supporting backtracking at all does cause real issues for reasonable programs, such as https://github.com/mvdan/sh/issues/558, https://github.com/mvdan/sh/issues/400, and this issue.

I did open https://github.com/mvdan/sh/issues/350 to discuss a potentially smarter solution, too, but decided against it in the end.

**Comment by rob-myers** [comment]
My use case is off-kilter, so thanks for considering.

I vaguely hoped a flag could be introduced e.g. `fallbackToLit`.

Rather than backtracking, literals could be created in tandem and 'fallen back to'.
However there's no reason why this should fit your implementation.

**Comment by mvdan** [comment]
That's an interesting idea. It has an extra cost in the best case scenario where no backtracking would be needed, but it also means we don't have to worry about buffering or seeking. I also don't have to implement a "go back in time" feature in the lexer and parser, which is nice.

This would most likely be limited to no nesting. That is, we would at most be parsing an input byte twice. Otherwise, something like `${a[${b[${c[$d{` would already result in parsing the following bytes sixteen times - it's exponential. I think any reasonable use of bash will at most use one level of ambiguity.

**Comment by rob-myers** [comment]
I decided that `get x[0].y` is better syntax anyway, so I will close this.

**Comment by mvdan** [comment]
Thanks for following up. For what it's worth, I'm coming around to the idea that we should do a reasonably limited version of ambiguous parsing. But I'm a bit short on time at the moment, so I can't really give an ETA unless someone volunteers their own time.

**Comment by mvdan** [comment]
> Rather than backtracking, literals could be created in tandem and 'fallen back to'.

I thought about this some more over the months, and I've filed https://github.com/mvdan/sh/issues/686 about it :)

Still no promise on an ETA, but now I'm pretty convinced we should do it.
