### ISSUE TITLE
syntax: position line number size is too small

### ISSUE THREAD

**Issue by zackw** [mvdan/sh#620]
shfmt's line counter seems to be only 16 bits wide and therefore wraps around on very long shell scripts.

```
$ perl -e 'for (1 .. 65534) { printf("cmd%d\n", $_) }; print "if\n"' | shfmt -p > /dev/null
<standard input>:65535:1: "if <cond>" must be followed by "then"
$ perl -e 'for (1 .. 65535) { printf("cmd%d\n", $_) }; print "if\n"' | shfmt -p > /dev/null
<standard input>:0:1: "if <cond>" must be followed by "then"
```

I was hoping to be able to use `shfmt -p > /dev/null` as an alternative to `bash -n`, as suggested in the README, for some very long (machine-generated) shell scripts I'm working with.  Not only is this a blocker for that usage in itself, it seems to derange the parser when compound commands cross the boundary:

```
$ perl -e 'for (1 .. 65534) { printf("cmd%d\n", $_) }; print "(cmd; cmd\n)\n"' | shfmt -p > /dev/null; echo $?
0
$ perl -e 'for (1 .. 65535) { printf("cmd%d\n", $_) }; print "(cmd; cmd\n)\n"' | shfmt -p > /dev/null; echo $?
<standard input>:0:7: statements must be separated by &, ; or a newline
1
```

**Comment by mvdan** [comment]
I was hoping noone would need such large line numbers :) The position type is as follows:

```
type Pos struct {
        offs      uint32
        line, col uint16
}
```

This allows for entire file sizes up to about 4 GiB, and the line and column numbers reach up to 65k, like you saw. The reason is so that, on 64-bit, a position only takes 64 bits as opposed to a larger amount of overhead like 128 bits. Remember that practically every node has a position, and some have multiple. I just verified that `unsafe.Sizeof(syntax.Pos{}) == 8)`, or 64 bits.

Lucky for me, my past self kind of saw this coming and didn't export the fields, but rather only exposed methods which return non-sized `uint`s. So at least we can change the underlying implementation without breaking anyone.

I can think of three options:

1) Keep the current limits, but fix the parser to work normally after the limit is hit.
2) Double the size of `Pos`, e.g. increasing line and column numbers to be 32-bit.
3) Something else, like using a 32-bit offset, a 22-bit line number, and a 10-bit column number.

Note that both options 2 and 3 would cause a small hit to performance, either by the increased memory sizes, or by the added bit arithmetic.

It looks like Go goes for option 2 in the new internal parser, so at least that seems to support option 2:

```
type Pos struct {
        base      *PosBase
        line, col uint32
}
```

**Comment by mvdan** [comment]
I've implemented 1 for now, since it felt like a good change to make anyway. The position numbers now also render as `?` when they've overflowed their size. This is a good change whatever bit size we settle with.

**Comment by zackw** [comment]
Some data: The longest shell script I have to hand is 1,173,156 lines long, and the longest single line in a shell script I have to hand is 10,028 characters long.  log<sub>2</sub> 1173156 + log<sub>2</sub> 10028 ≈ 33.45 so there's no way to fit both of those into a 32-bit word.  However, the worst-case script is a self-extracting archive whose actual code is only 438 lines long, followed by 287MB of binary data.  The *second* longest shell script I have to hand is only 102,453 lines long.  And the 10,028-character line occurs inside a here-document.  A more realistic "longest line" is ~1000 characters, although looking at what it does, it could easily need to be longer in the future (it's an egrep invocation with a long regexp and we keep discovering more cases we need to add to it).

For what I'm using this library for, accurate line numbers are more important than accurate column numbers, so if you decide to go with option 3, a 22:10 or even a 24:8 split would be fine by me, but a 18:14 split is what fits the above data.

I don't know how practical this is, but an alternative that avoids putting low limits on *either* line or column numbers would be to keep an array on the side whose indices are line numbers and whose values are file offsets.  Then `Pos` could be 

```
type Pos struct {
        offs  uint32
        line  uint32
}
```

and you would compute the column number for a position `p` as `p.offs - line_starts[p.line] + 1`.  If line numbers are not needed very often, you could even drop the line field from `Pos` and recover it from the line-starts table by binary search whenever actually needed.

(I regret to say I cannot help you implement anything on account of I do not actually speak Go.)

**Comment by mvdan** [comment]
> For what I'm using this library for, accurate line numbers are more important than accurate column numbers, so if you decide to go with option 3, a 22:10 or even a 24:8 split would be fine by me, but a 18:14 split is what fits the above data.

I actually agree that accurate line numbers matter more, especially to humans. If a file has tons of lines with tons of columns each, getting to the right line is more important than getting to the right column. Plus, like you say, "tons of lines" is more common in programming languages, and especially in shell - some features like heredocs force the use of newlines.

One could also "recreate" the column number if they so desire, assuming they can seek through the input file. The algorithm would be something like:

* Seek to the offset byte counter
* Read backwards until a newline character is found
* Count the number of bytes between the newline character offset and the position offset

Since right now we have a 16:16 split, I think the smallest step we could take probably makes sense, meaning a 18:14 or 20:12 split. If that turns out to still not be enough, and we don't want to further shrink column numbers, then we can discuss doubling the position size.

>  If line numbers are not needed very often, you could even drop the line field from `Pos` and recover it from the line-starts table by binary search whenever actually needed.

This is actually what v1 did, a mechanism copied from the older go/token package. See https://golang.org/pkg/go/token/#Pos and https://golang.org/pkg/go/token/#FileSet.Position.

This results in a smaller memory footprint without low limits, but it's much worse in terms of user experience and flexibility for edits. For example, a position alone is nearly meaningless unless you also have the context, so you end up needing to keep the context around explicitly, or attach it to an entire File. Any sort of advanced use case, such as removing or adding one empty line, also requires touching the internals directly, which is very easy to mess up.

The new Go syntax package uses context-free positions for the reasons above, and I copied that change of heart a few years ago.

**Comment by mvdan** [comment]
Switching from the 16:16 split to 18:14 is done. Feel free to leave a comment here or open a new issue if you think we should do a different split instead, like 20:12.
