### ISSUE TITLE
interp: implement features used by direnv

### ISSUE THREAD

**Issue by zimbatm** [mvdan/sh#624]
Hi @mvdan,

I spent a bit of time trying to integrate gosh and direnv. My approach so far has been to set the DIRENV_BASH environment variable to point to `gosh`.

Here are some things that I have found:

Bash was invoked with `-norc` and `-noprofile` which `gosh` doesn't understand.

`set -ueo pipefail` seems to not be understood by the interpreter.

Same for `shopt -s nullglob`

Finally, I got a panic on the `trap` builtin. I am relying on this for the bash integration but if gosh was made part of the code, I think I could be work around it.

In the good news, `gosh stdlib.sh` seems to work, so the whole script gets loaded.

I pushed some of the workarounds in https://github.com/direnv/direnv/pull/703 if you want to try it out for yourself.

<3

**Comment by mvdan** [comment]
Good to hear from you!

> Bash was invoked with `-norc` and `-noprofile` which `gosh` doesn't understand.

I should note that `gosh` is not meant to be a full-blown shell or a replacement for Bash. Historically it has just been an easy way to try or test the interpreter. As such, there are no plans to teach it about "rc" or profile files. Given that your tool is in Go, you'd benefit a lot more from using the parser and interpreter directly, I think.

> set -ueo pipefail seems to not be understood by the interpreter.
> Same for shopt -s nullglob

Thanks, those sound like something we should implement. I'll take a look.

> Finally, I got a panic on the `trap` builtin. I am relying on this for the bash integration but if gosh was made part of the code, I think I could be work around it.

I think `trap` is one of the few shell features we can't properly implement in Go because we can't fork. If a Go program interprets two shell programs concurrenty (with two interpreters) and both programs trap the same signal, they'd conflict because they're running on the same process. We could, however, introduce a "single process" mode as described in https://github.com/mvdan/sh/issues/171. If you can avoid `trap` altogether, that's probably going to be the simplest way.

**Comment by zimbatm** [comment]
Completely agree about `-norc`. Ultimately the goal is to embed the go code instead of invoking `gosh`.

Regarding `trap`, I only care about the `EXIT` and `ERR` callbacks. Those can be implemented by adding an "eval" step when the program terminates and doesn't need to handle process signals. Maybe that subset would be acceptable?

I use those quite often for cleanup scenarios like this:
```sh
workdir=$(mktemp -d)
trap 'rm -rf $workdir' EXIT

# ... do the actual work here
```
They are a bit like `defer` in Go, except that it's limited to one per program.

**Comment by mvdan** [comment]
Indeed, we could probably safely implement `EXIT` and `ERR` in the interpreter. The ones that require real per-process syscalls could simply error unless the "single process" mode is enabled.

**Comment by zimbatm** [comment]
Direnv uses `trap` to dump the environment variables at the end of the evaluation. Once embedded into direnv I could bypass that and read the variable from the interpreter state directly. Just to say that it's not strictly necessary.

**Comment by mvdan** [comment]
The PR you raised with the `nounset` test case is now fixed, as is `set -ueo pipefail`. I'll do `nullglob` later today, which shouldn't be too difficult.

Perhaps you can try again and tell me what other bugs or missing features you find, if any. It seems like `-norc`, `-noprofile`, and `trap` aren't necessary for this use case.

**Comment by mvdan** [comment]
I've split up support of `trap` with the shell signals into https://github.com/mvdan/sh/issues/635. Similarly, you created a separate issue about "type -p", which is usefull.

I think it's best to have one issue for each missing feature or bug, for the sake of being able to track what's left to do. I'm going to close this issue for now, since the original two issues have been fixed, and we've created the separate ones for the next blockers. Thanks again!
