### ISSUE TITLE
Request: Build for darwin_arm64

### ISSUE THREAD

**Issue by flying-sausages** [mvdan/sh#642]
Apple Silicon is nice! It would be great if you could compile those bins for us as well :) Thanks in advance!

**Comment by mvdan** [comment]
Indeed, I was planning this. For now I've just been building for the platforms which are first-class ports of Go. `darwin/amd64` has been one for a while, and Go 1.16 adds support for `darwin/arm64`, so I think it should also become a first class port soon as well. I'd rather not make exceptions until then, because it opens the "what about <some other platform>" can of worms, and because building from source takes about ten seconds on a light laptop.

**Comment by flying-sausages** [comment]
Understood, thanks!

For those who want the native bin unofficially in the meantime, it builds with `brew install shfmt -s` if you have the native setup. Hopefully will be bottled soon.

**Comment by mvdan** [comment]
To recap for those finding this thread later - Go is adding official support for darwin/arm64 in 1.16, which is due to come out in a few weeks. At this moment they've only released 1.16beta1, which has over twenty known bugs. It would be unwise of me to publish binaries for this platform before the final 1.16 release is out.

**Comment by mvdan** [comment]
Luckily, 1.16 is going to release with darwin/arm64 as a first-class port already, so it's a no-brainer to ship binaries for it too here.

The only detail to worry about is timing a release with Go's release. I don't want to modify the binaries for a previous release, as that could break existing users of said binaries, especially if they are (correctly) pinning them via hashes.

**Comment by flying-sausages** [comment]
Could just mark it as a pre-release for darwin_arm64 only, and then make a proper batch the next time around I would assume. Also, I think there are currently bottles in brew for shfmt if I'm not mistaken, FYI

**Comment by mvdan** [comment]
https://github.com/mvdan/sh/issues/682 warrants a v3.2.3 release, and I think Go 1.16.1 is about to be released, so I'll time those together.

**Comment by mvdan** [comment]
On second thought, this week we're only getting a security release, so let's not wait any longer.

**Comment by mvdan** [comment]
Alright, darwin/arm64 included here: https://github.com/mvdan/sh/releases/tag/v3.2.4
