### ISSUE TITLE
interp: local variables are immutable

### ISSUE THREAD

**Issue by twilly** [mvdan/sh#674]
f4c774aa15046ef006508e182fde10c4b56876fa introduced a regression where local variables are immutable.

`f() { local a; a=bad; a=good; echo $a; }; f` should print "good" but instead prints "bad." I pushed a test case at https://github.com/mvdan/sh/compare/master...twilly:bug-locals-are-immutable.

**Comment by twilly** [comment]
Some quick tracing is implicating `a=good` is taking the global scope update https://github.com/mvdan/sh/blob/master/interp/vars.go#L37 instead of the function scope.

**Comment by twilly** [comment]
A new `expand.Variable` has a default value of `Local:false`, which is passed to `overlayEnviron.Set`. Taking the var modify path doesn't preserve the Local flag, which is preserved (along with Exported and ReadOnly) on the initial value.

Preserving the Local flag does let this test pass.

```patch
--- a/interp/vars.go
+++ b/interp/vars.go
@@ -66,6 +66,7 @@ func (o *overlayEnviron) Set(name string, vr expand.Variable) error {
                }
        }
        // modifying the entire variable
+       vr.Local = prev.Local || vr.Local
        o.values[name] = vr
        return nil
 }

```

**Comment by mvdan** [comment]
If all tests including your new one pass, I would say it's probably the right fix. A lot of the variable assignment logic is driven by getting the tests to pass, since the behavior of all those edge cases is usually not well documented. The assumption is that, over time, we'll get the right behavior with plenty of tests.

It's perhaps silly to do it this way via reverse engineering, but I think trying to mimic the original Bash C code would be worse - and would mean possible licensing issues.

**Comment by twilly** [comment]
SGTM. Let's TDD this to the end of the world.

PR incoming. :)
