### ISSUE TITLE
cmd/shfmt: regression between 3.1.2 and 3.2.0 on multiple paths with -d

### ISSUE THREAD

**Issue by tianon** [mvdan/sh#682]
:wave:

I'm not sure exactly what did it, but it appears there's a regression in 3.2+ where running `shfmt -d file1.sh file2.sh` with multiple files that have bad formatting will only display the diff for one of them! :grimacing:

Minimal reproducer:

```console
$ cat file1.sh
#!/bin/bash
foo; bar; baz
$ cat file2.sh
#!/bin/bash
foo; bar; baz; buzz

$ shfmt -version # on 3.1.2
4ac084e
$ shfmt -d file1.sh file2.sh
--- file1.sh.orig
+++ file1.sh
@@ -1,3 +1,5 @@
 #!/bin/bash
-foo; bar; baz
+foo
+bar
+baz
 
--- file2.sh.orig
+++ file2.sh
@@ -1,3 +1,6 @@
 #!/bin/bash
-foo; bar; baz; buzz
+foo
+bar
+baz
+buzz
 
$ shfmt -version # again, but on 3.2.0
v3.2.0
$ shfmt -d file1.sh file2.sh
--- file1.sh.orig
+++ file1.sh
@@ -1,2 +1,4 @@
 #!/bin/bash
-foo; bar; baz
+foo
+bar
+baz

```

(I've also verified that the behavior is the same on 3.2.2.)

Apologies if this is already filed somewhere (or if it was an intentional change); I looked but couldn't find anything obviously related. :sweat_smile: :heart:

**Comment by mvdan** [comment]
Thank you for reporting this, that's embarassing. Starting in v3.2, if any of the paths results in an error, we'd just stop and not process any more files. This includes non-empty diffs, since they result in a non-zero status code, so they're treated as an error.

Fix incoming. Depending on how soon I do v3.3.0, I might not bother with a backport to v3.2.x.

**Comment by mvdan** [comment]
On second thought, Go 1.16.1 is about to be released and some people wanted M1 Mac binaries, so I'll do a v3.2.3.
