### ISSUE TITLE
syntax: error parsing "#" in glob

### ISSUE THREAD

**Issue by libertypi** [mvdan/sh#685]
The following line:
```bash
arr=([^\#]*)
```
will cause shfmt to report error: `^ must follow an expression`

But it's valid bash. 

However, `for f in [^\#]*; do :; done` works fine. So I guess it has something to do with array syntax parsing.

**Comment by mvdan** [comment]
Hm, what version are you running and how can I reproduce that error?

```
$ shfmt <<<'arr=([^\#]*)'
<standard input>:1:7: ^ must follow an expression
$ shfmt -p <<<'arr=([^\#]*)'
<standard input>:1:5: arrays are a bash/mksh feature
$ shfmt -version
v3.3.0-0.dev.0.20210311224605-8f4a18d1a615
```

In any case, this sounds like https://github.com/mvdan/sh/issues/558, which unfortunately doesn't have an easy solution.

I do plan to support simple cases of ambiguity, because I do think we should support parsing inputs like yours. Though it won't be an easy change to make.

**Comment by libertypi** [comment]
> Hm, what version are you running and how can I reproduce that error?
> 
> ```
> $ shfmt <<<'arr=([^\#]*)'
> <standard input>:1:7: ^ must follow an expression
> $ shfmt -p <<<'arr=([^\#]*)'
> <standard input>:1:5: arrays are a bash/mksh feature
> $ shfmt -version
> v3.3.0-0.dev.0.20210311224605-8f4a18d1a615
> ```
> 
> In any case, this sounds like #558, which unfortunately doesn't have an easy solution.
> 
> I do plan to support simple cases of ambiguity, because I do think we should support parsing inputs like yours. Though it won't be an easy change to make.

My bad, the message is from another file. This error is "^ must follow an expression".
