### ISSUE TITLE
suppress () after function

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [mvdan/sh#694]
I see that shfmt add `()` after `function`. I want to suppress the addition of (). Is there a way to do it?

```
$ cat main.sh
#!/usr/bin/env bash

function f {
        shfmt <"$BASH_SOURCE"
}

f
$ ./main.sh
#!/usr/bin/env bash

function f() {
        shfmt <"$BASH_SOURCE"
}

f
```

**Comment by mvdan** [comment]
Do you have a reason in particular? The formatter is meant to be as consistent as possible, so adding more ways to print the same program is generally not a good idea.

**Comment by prRZ5F4LXZ** [comment]
I use bash. In bash () is not necessary. Therefore, I don't want to add them automatically.

**Comment by mvdan** [comment]
Fair enough. The point of shfmt is consistent formatting, though, and using `()` is most consistent with the rest of the syntax.

But actually, it's your lucky day, because we had to do this for the sake of ksh support, see https://github.com/mvdan/sh/commit/943b9d07870c1e2e7d31db2c120e68238d0006e8. If you're using shfmt v3.2 or later, it should just work.

**Comment by mvdan** [comment]
I'm going to guess that you were using an older shfmt. This just works on v3.2.0 or later.
