### ISSUE TITLE
Request to support padding inside $(( or (( arithmetic expansion

### ISSUE THREAD

**Issue by bushidocodes** [mvdan/sh#695]
First off, `shfmt` is amazing! I've been using Exercism to level up my bash-fu, and I've really appreciated this tool in my workflow. I can't say I'm surprised that it's a Gopher spreading the love of gofmt to the masses.

In a recent kata, an Exercism mentor suggested to me that many folks like to pad the inside of `((` similar to `[` or `[[`, presumably for a bit of consistency. 

So this example:

```bash
declare -i number=0
((number++))
echo "$number"
```
Would become:
```bash
declare -i number=0
(( number++ ))
echo "$number"
```

I don't think `shfmt` supports this style, so I figured it's worth opening a feature request assuming that a fair number of folks have this preference.

**Comment by mvdan** [comment]
Normally I'd say that this is by design, because shfmt is meant to have almost no formatting knobs. Lucky for you, this is already planned as part of generalizing an existing feature for v4; see https://github.com/mvdan/sh/issues/544.

I can't give an ETA because such a change would be backwards-incompatible, but I do plan to look at preparing a v4 release by the end of the year.

**Comment by bushidocodes** [comment]
Understood! I appreciate the quick feedback. 🙌 I'll close out the issue to help keep your tracker clean.
