### ISSUE TITLE
How to just let shfmt fix indentation problems but not anything else?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [mvdan/sh#696]
I just want shfmt to fix any indentation problems, but not to change anything else in my program.

```
$ shfmt <<< '((x==y))'
((x == y))
$ shfmt <<< '((x==     y))'
((x == y))
$ shfmt <<< '(x; y)'
(
	x
	y
)
```

In the first two examples, spaces are added or deleted. I want to disable these changes. In the 3rd example, I've already decided to put two commands be in a single line. But shfmt break it into two lines. I want to disable this.

Basically, I only want shfmt to fix errors in indentation, but not change anything after the first non-space character in a line.

Can this feature be added?

**Comment by mvdan** [comment]
Sorry, but that's opposite to the tool's core purpose. It's a formatter, and by design pretty opinionated.

It does obey the user's choice in some ways, but not others. If you want to be in charge of all spaces and newlines, you shouldn't use a formatter.

It would certainly be possible to write a tool similar to shfmt on top of [the same library](https://pkg.go.dev/mvdan.cc/sh/v3/syntax), and for example only alter the indentation. But that would be a very different tool to shfmt, and not really a proper formatter, so I have no plans for that kind of tool right now.
