### ISSUE TITLE
shfmt is not compatible with shellcheck

### ISSUE THREAD

**Issue by c02y** [mvdan/sh#697]
I use shfmt for formating bash scripts in both vim and emacs, but when I edit a bash script and auto format it, I found out that the final result of the bash script has a lot of warning and errors when I check it using shellcheck such as:
```
^------^ SC2086: Double quote to prevent globbing and word splitting.

^--^ SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).

^-- SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.

 ^-- SC2039: In POSIX sh, read -p is undefined.
```

Just be curious, is there any bash shell standard? Why shfmt are using the current syntax style that is different from shellcheck?

Which one is right, shfmt or shellcheck?

**Comment by mvdan** [comment]
I think you're getting a bit confused. shfmt is a code formatter, and shellcheck is a linter that tries to find bugs.

shfmt won't automatically fix shellcheck's warnings, because most of them are not about formatting/style.

Similarly, making shellcheck happy won't make shfmt happy directly.

You should be able to use both tools at once. If for any reason that doesn't work, please file issues with clear details for me to reproduce.

**Comment by c02y** [comment]
Sorry, my mistake. Close it.
