### ISSUE TITLE
syntax: `Quote` should probably return `""` instead of empty for an empty string

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#763]
Originally reported at https://github.com/go-task/task/issues/609.

If you quote an empty string the returned value won't work in a concatenated Bash script: ` == 'foo'` vs. the desired `"" == "foo"`.

I think it'd make sense to fix this here, because more people could use the returned value inside Bash scripts. But if you don't think so, I gonna do this fix on the Task side.

**Comment by mvdan** [comment]
This actually got caught by the fuzzer after I improved it a little, and is already fixed on master; see https://github.com/mvdan/sh/commit/92eab20da20af9c4005294abf937e387d87c8407.

I'm preparing for a v3.4.1 release soon, but I actually forgot to cherry-pick that into https://github.com/mvdan/sh/tree/v3.4 - oops. Fixed now. I plan on doing the release in a few days; you can `go get` the HEAD of that branch in the meantime.

I'm going to close this for now, as the bug is already fixed. Thanks!
