### ISSUE TITLE
syntax: error parsing tilde expansions when declaring an associative array

### ISSUE THREAD

**Issue by lollipopman** [mvdan/sh#764]
Bash allows using tilde expansions when declaring associative arrays:

```
#!/bin/bash
HOME=/home/butter
declare -A dirs=(
	[~/]=home
)

declare -p dirs
```

output:

```
declare -A dirs=([/home/butter/]="home" )
```

but shfmt is unable to parse the file:

```
$ shfmt ~/test.sh
/home/hathaway/test.sh: /home/hathaway/test.sh:5:3: ~ must be followed by an expression
```

Thanks for all your work on `shfmt`!

**Comment by mvdan** [comment]
Hm, I fear this falls under the first item in https://github.com/mvdan/sh#caveats. When we see `foo=([~/`, we have no way to tell if the index is an arithmetic expression (indexed array) or a string (associative array). You can typically disambiguate that by using quotes, like `foo=(["~/"]=home)`, but I imagine that defeats the purpose as tilde expansion is supressed. How about `foo=([""~/]=home)`, to act as a hint?

Worth noting that Bash fails here unless you use `declare -A` to clarify that the array is indeed associative. However, we can't pull that trick in our parser, because our parser is fully static. For instance:

```
# arr is declared elsewhere

arr[~/]=home # should this fail? we can only know for sure at run time.
```

**Comment by mvdan** [comment]
Personally, in this particular scenario, I'd go with `["${HOME}/"]` or somesuch, to avoid tildes entirely. They're just tricky to use in index expressions without introducing ambiguity.

**Comment by mvdan** [comment]
I'm going to close this for now, as the caveats section in the README covers this.

Potentially, we could solve this via https://github.com/mvdan/sh/issues/686, but note that this is not really a case of ambiguous parsing. Rather, that the static parser can't know if an array is indexed or associative ahead of time. Still, if we see `[~/]`, we could use 686 to parse the index expression as a literal string, given that parsing as an arithmetic expression will fail. If the script is interpreted and the array is indexed, evaluating that arithmetic expression would fail.
