### ISSUE TITLE
interp: test -d "" succeeds when it should fail

### ISSUE THREAD

**Issue by raylee** [mvdan/sh#781]
I've been testing shell portability for a silly script of mine, and hit upon a behavior difference with the built-in command `test`:

```shell
for shell in sh bash dash zsh ksh csh tcsh gosh; do 
    printf "%s\t" "$shell "
    $shell -c "test -d '' && echo true || echo false"
done
```
```shell
sh 	false
bash 	false
dash 	false
zsh 	false
ksh 	false
csh 	false
tcsh 	false
gosh 	true
```

I noticed this as I had code relying upon [ -d "${XDG_CACHE_HOME:-}" ] to fail when the env var was unset.

Poking around the code for a few minutes led me to [Runner.absPath](https://github.com/mvdan/sh/blob/4a4c1600341f6413719f5e8a50105b8d13a96d6d/interp/builtin.go#L870-L875). It has a few callsites however, and I haven't audited them to see if the obvious change of checking for `path == ""` would impact them.

**Comment by mvdan** [comment]
Thanks for opening this detailed issue!

`absPath` currently assumes its parameter is non-empty. On an empty string, it will append the current directory to it, which isn't right. We should tweak the logic to return an empty string if the input parameter is also empty.

We have plenty of tests already, but we should add empty string tests for the places that call it, such as `test -d ''`, `cd ''` and `test -x ''`.

I'll mark this as a good first issue, because it should be a fairly straightforward fix :) Happy for you to take a crack at it, too!

**Comment by raylee** [comment]
> Happy for you to take a crack at it, too!

My pleasure. `absPath` felt like a good place to check in.

I've opened a PR with the minimal change to fix this. Turns out there's a three different places doing absPath-like things. Let me know if you'd like a follow-up commit which unifies those.
