### ISSUE TITLE
Heredoc formatting.

### ISSUE THREAD

**Issue by bartik** [mvdan/sh#791]
### Issue
**Input (x.out):**
discover() {
cat <<-EOF_INI >"${_arg_tmp}${_arg_prefix}${_arg_host}.ini"
host=${_arg_host}
EOF_INI
}
**Output:**
shfmt x.out
x.out: x.out:2:5: unclosed here-document 'EOF_INI'
**Expected**
discover() {
**\t**cat <<-EOF_INI >"${_arg_tmp}${_arg_prefix}${_arg_host}.ini"
**\t\t**host=${_arg_host}
**\t**EOF_INI
}

### Correct
**Input**
cat <<-EOF_INI >"${_arg_tmp}${_arg_prefix}${_arg_host}.ini"
host=${_arg_host}
EOF_INI
**Output/Expected**
shfmt x.out
cat <<-EOF_INI >"${_arg_tmp}${_arg_prefix}${_arg_host}.ini"
**\t**host=${_arg_host}
EOF_INI

### Version
shfmt -version
v3.4.2

### Question
When using -i 4 in the command abowe (shfmt -i 4 x.out) but a here document should be created (leading tabs) are tabs used despite the -i 4 ?

**Comment by mvdan** [comment]
`<<-` only supports tab indentation, not spaces. If you use space indentation, they won't be stripped from the heredoc content.

So we only have two options when a flag like `-i 4` is used with `<<-` heredocs - either tab indentation, which can lead to inconsistency in indentation, or no indentation at all. We go for the latter. I don't think there's a better option.

Is this what this issue is about, or are you also reporting a parsing error when there shouldn't be one?

**Comment by bartik** [comment]
The problem is the wrong parsing. The heredoc in function as shown in **Issue/Input** should not give the error _unclosed here-document 'EOF_INI'_ but should format the text as shown in **Issue/Expected**.

**Comment by bartik** [comment]
The problem seems to be that the CR confuses the parser because it seemingly expects LF directly after the closing label. Converting the source file entirely to LF solves the problem (and converting backt to CRLF brings the problem back). I'm running on windows. I suppose there is only \n in the code used so migt be a thing with how the windows binaries are created. Thanks for your efforts. For me the issue is solved.

**Comment by FFengIll** [comment]
Wanna ask why it warn "unclosed here-document " when use cmd like "cat <<EOF" ?
And can we pass it?
