### ISSUE TITLE
Docker image latest and latest-alpine with wrong version

### ISSUE THREAD

**Issue by nvuillam** [mvdan/sh#805]
Hi,

We noticed that official docker images **latest** and **latest-alpine** tags do not contain the latest version (they contain a 3.5.0 unreleased version)

Would it be possible to update them so latest and latest-alpine contain 3.4.2 ?

```
$ docker run -it mvdan/shfmt:latest --version
v3.5.0-0.dev-49-g976895f5
```

Related to MegaLinter issue -> https://github.com/megalinter/megalinter/issues/1223

Thanks for your tool and best regards :)

**Comment by mvdan** [comment]
See https://github.com/mvdan/sh/issues/740. The `latest` tag is tracking the latest development version in `master`. I'll soon introduce a `v3` docker tag that will instead track the latest stable v3 version; today that's v3.4.2, but soon it would be v3.4.3 or v3.5.0.

I'm closing this issue, because the previous one already tracks this work :) If you disagree with how our `latest` tag works, see the discussion there.

**Comment by nvuillam** [comment]
What you call latest is probably an alpha or a beta, but as long as I know your rule I'll deal with it, thanks for your reply :)
