### ISSUE TITLE
Formatting shell commands in eval command

### ISSUE THREAD

**Issue by Julien-Elie** [mvdan/sh#809]
Would it be possible to consider the argument of the eval `command`, when it is a string, as a candidate to being reformatted?

```
#!/bin/sh
echo a > test
eval "echo a > test"
```

gets reformatted:

```
#!/bin/sh
echo a >test
eval "echo a > test"
```

The string passed as an argument to the `eval` command could be considered as a shell command to reformat, couldn't it?

**Comment by mvdan** [comment]
The short answer is we shouldn't do this; we don't parse what is inside `eval` arguments. In fact, we treat eval arguments like any other word, because eval is precisely about parsing the string at run-time, like `eval "$src"`.

In fact, we used to parse the eval arguments as shell upfront, as you can [see here](https://github.com/mvdan/sh/commit/d4ffb0e7ff39fa0bfbe791dfae9b23aaffe72968#diff-a8e82a9ba553aa2b21ac3492717a2f1c3bf1276bdc4343cab175352e31c123fcR199), but we stopped doing that because it had many disadvantages. Some eval strings aren't valid shell before being expanded, for example.

If you want to apply formatting to a script to evaluate at run-time, I suggest alternatives:

* Keep the eval, but place the source in a separate shell file, which you can format normally.
* Avoid the eval entirely, assuming you don't need arbitrary syntax at run-time.

**Comment by mvdan** [comment]
Indeed. If you didn't need to inject arbitrary syntax at run-time, you'd just unquote the shell code :)
