### ISSUE TITLE
interp: add Dir and Env options to Runner

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#84]
Thank very much for this lib. It works like a charm!

[Task](https://github.com/go-task/task) currently runs commands using `sh -c "command"`. Unfortunaly, Windows don't have `sh` (unless you are on Git Bash or Cygwin), so it currently fallsback to `cmd /C "command"`, but them of course aren't compatible.  This lib will make it possible to write commands that runs anywhere.

The following options would be useful:

- `Dir`: to set the path the command will run.
- `Env`: specific environment variables for the command. These two exists on [`exec.Cmd`](https://golang.org/pkg/os/exec/#Cmd).
- `Context` for cancelable commands.

**Comment by mvdan** [comment]
> Thank very much for this lib. It works like a charm!

Cheers! Out of curiosity, how did you find out about it? I only proposed it two weeks ago and started implementing a week ago.

> This lib will make it possible to write commands that runs anywhere.

Sounds like a good idea!

> Dir: to set the path the command will run
> Env: specific environment variables for the command. These two exists on exec.Cmd

Yep, can do. The way these two work is global at the moment (`os.Chdir` and `os.Getenv`), which is terrible since it won't easily allow for multiple interpreters running at once. So I need to rewrite this part anyway.

> Context for cancelable commands.

I already have a TODO about this - I'm going to break it into its own separate issue to keep this one lighter.

**Comment by mvdan** [comment]
Also, if you find you need more fields, more methods or more helper functions, please open separate issues for each one.

I know I'm missing easy ones like `CombinedOutput`, but I wanted to keep things simple for the prototype implementation.

**Comment by mvdan** [comment]
And of course, patches are welcome :)

**Comment by andreynering** [comment]
> Out of curiosity, how did you find out about it? I only proposed it two weeks ago and started implementing a week ago.

I actually just searched on Google for a sh interperter written in Go.
