### ISSUE TITLE
Expose `ToJson` and `FromJson` methods

### ISSUE THREAD

**Issue by JounQin** [mvdan/sh#885]
via https://github.com/mvdan/sh/issues/760#issuecomment-1120420888

`sh-syntax` (WASM) is about 2x faster than `mvdan-sh`

https://github.com/rx-ts/sh-syntax/blob/main/benchmark/benchmark.txt

**Comment by mvdan** [comment]
You mean as exported Go APIs, since currently `-tojson` is not?

**Comment by JounQin** [comment]
> You mean as exported Go APIs, since currently `-tojson` is not?

Right, I need them in `sh-syntax`.

**Comment by JounQin** [comment]
A notice for WASM, we'd better not use `reflect` to generate `json`, because it could be broken, I'm using [`easyjson`](https://pkg.go.dev/github.com/mailru/easyjson) at `sh-syntax`, see https://github.com/un-ts/sh-syntax/blob/main/processor/structs_easyjson.go

**Comment by JounQin** [comment]
> You're of course free to use your own implementation.

I'm not sure how to. 😅

`sh-syntax` depends on this go library, if it depends on `reflect` in `ToJson`, how can I override it? Provide another copy on my side? Would it be hard to maintain?

Sorry I'm very new bee for go lang. Could you help to give me some advices?

**Comment by mvdan** [comment]
Right, size matters. That's a reason to not use libraries like easyjson, in fact, because they are often many times bigger than `encoding/json` :)

**Comment by JounQin** [comment]
`encoding/json` is not fully supported by `tinygo`, so I have to use `easyjson` instead. 🤣

**Comment by mvdan** [comment]
Looks like it is only blocked on `reflect.StructOf` (https://tinygo.org/docs/reference/lang-support/stdlib/#encodingjson), which I'm also using for the new version of "to JSON", since Go maps aren't ordered. I've left a comment at https://github.com/tinygo-org/tinygo/issues/2115#issuecomment-1183304339.

> `easyjson` replaces `reflect` in this case.

Right, though easyjson uses code generation, so I'm fairly sure that the output size suffers because of it.

In the future, I can remove the use of reflection by swapping encoding/json with the token encoder and decoder in https://github.com/go-json-experiment/json. I don't want to do that right away, as I want to get "from JSON" working well first.

**Comment by mvdan** [comment]
Thinking outloud: this API should not be in the syntax package, because we don't want to require a JSON library to be able to parse shell.

**Comment by JounQin** [comment]
> Thinking outloud: this API should not be in the syntax package, because we don't want to require a JSON library to be able to parse shell.

What do you think should we do in `sh-syntax` package then?

**Comment by mvdan** [comment]
Nothing has to change there. It's just that instead of having the API like `ToJSON(io.Writer, syntax.Node)` in the `mvdan.cc/sh/v3/syntax` package, I'll probably put it somewhere else like `mvdan.cc/sh/v3/syntax/typedjson`. You can use both packages in your wasm code.
