### ISSUE TITLE
Please support curly_bracket_next_line as alias of function_next_line in shfmt

### ISSUE THREAD

**Issue by ale5000-git** [mvdan/sh#930]
Hi,
`curly_bracket_next_line` is listed in the official wiki: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#ideas-for-domain-specific-properties
and it seems to do the same of `function_next_line`.

So it would be nice to support it, please.

**Comment by mvdan** [comment]
See https://github.com/mvdan/sh/issues/721. Currently, the option does not apply to all `{` tokens, only the function ones. That issue is about changing the option to make it more consistent.

I guess it's then up for debate whether we should make `curly_bracket_next_line` an alias for the existing editorconfig setting we already have for this shfmt flag. My thinking is probably not, given that with 721 implemented, the flag would also affect `do` and `then`, which are clearly not curly brackets. But I could be convinced otherwise. Perhaps leave a comment there and see what others think.

Closing this for now in favor of 721. I definitely don't think we should change the existing `function_next_line` given how we want to replace it.
