### ISSUE TITLE
Associative array key with hyphen breaks in v3.6.0

### ISSUE THREAD

**Issue by DannyBen** [mvdan/sh#956]
This is a new bug that did not exist in 3.5.1.

### Test code

```bash
#!/usr/bin/env bash

if [[ -n "${args[--no-cache]:-}" ]]; then
  echo "ok"
fi
```

### Actual output

```diff
➜ shfmt -d -i 2 test.sh
--- test.sh.orig
+++ test.sh
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash

-if [[ -n "${args[--no-cache]:-}" ]]; then
+if [[ -n "${args[--no - cache]:-}" ]]; then
   echo "ok"
 fi
```

### Expected output

Empty, no change.

**Comment by mvdan** [comment]
I don't think I've ever had a regression reported against a new release so quickly :)

The change looks correct; the key isn't quoted, so we assume it is an arithmetic expression, hence the spacing around the `-` operator. See the "caveats" section in the README. The way to tell the parser that your key is a string is to quote it, as otherwise it's ambiguous.

I'm not sure I can reproduce the regression either; the previous release results in the same output:

```
$ shfmt -version
v3.5.1
$ cat f.sh
#!/usr/bin/env bash

if [[ -n "${args[--no-cache]:-}" ]]; then
  echo "ok"
fi
$ shfmt -d f.sh
--- f.sh.orig
+++ f.sh
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
 
-if [[ -n "${args[--no-cache]:-}" ]]; then
-  echo "ok"
+if [[ -n "${args[--no - cache]:-}" ]]; then
+	echo "ok"
 fi
```

**Comment by DannyBen** [comment]
Weird, but I also see the same issue now with 3.5.1. Maybe I was wrong about it working differently.
Its just that shfmt did not report anything on my scripts other than the case comment indentation issue I reported.

I still think this is a bug, not a caveat.
This script passes `shellcheck`, which means in my book that this is a valid way of providing associative key. Can't the rule that checks for hyphens be modified to avoid a pattern that indicates it is an array?

**Comment by DannyBen** [comment]
Understood.  I will adjust my code accordingly, with the objective of all the code generated by bashly to be shfmt compliant (https://github.com/DannyBen/bashly/issues/313).

Thanks for the release, I will close this issue then.
