### ISSUE TITLE
editorconfig ignored with --ln bats

### ISSUE THREAD

**Issue by cdleonard** [mvdan/sh#975]
Here is my editorconfig:

```
[*]
# like -i=4
indent_style = space
indent_size = 4
```

main.sh
```
#! /bin/bash

main() {
    echo aa
}
main "$@"
```

```
$ shfmt main.sh
#! /bin/bash

main() {
    echo aa
}
main "$@"
```

```
$ shfmt --bats main.sh
#! /bin/bash

main() {
        echo aa
}
main "$@"
```

As far as I understand editorconfig only works based on file globbing so language dialects should have no impact.

Tested using shfmt 3.4.3-1 from ubuntu 22 and also the mvdan/shfmt docker image

**Comment by mvdan** [comment]
This is working as documented, per https://github.com/mvdan/sh/blob/d806889c9dcc49e5885942b1de63fae147875dc8/cmd/shfmt/shfmt.1.scd#description:

> If any EditorConfig files are found, they will be used to apply formatting options. If any parser or printer flags are given to the tool, no EditorConfig files will be used. A default like -i=0 can be used for this purpose.

The "language" flags are parser flags.

The thinking here was that we don't want to support options from multiple sources, because that could easily get confusing. The logic uses either EditorConfig or explicit flags, which I reckon is OK given that we don't have many flags to begin with.

**Comment by cdleonard** [comment]
This is bizarre - the --bats option is required in order to process .bats files at all without syntax errors. Even if this is "behaving as documented" the fact that editorconfig can't be used for .bats is confusing and never the desired outcome.

Also - the general convention in most tools is that arguments on the command line override config files.

I really don't see why --bats would interact with editorconfig at all - the editorconfig spec says nothing about how to handle language dialects.

**Comment by mvdan** [comment]
> This is bizarre - the --bats option is required in order to process .bats files at all without syntax errors.

That should be working. Can you provide an example?

**Comment by cdleonard** [comment]
> > This is bizarre - the --bats option is required in order to process .bats files at all without syntax errors.
> 
> That should be working. Can you provide an example?

I checked again and this apparently happens with the shfmt from ubuntu22 (3.4.3-1). The dockerized version of shfmt can indeed parse .bats even without `--ln bats`. So maybe it was fixed recently?

Anyway - I still believe that dialect options should not block editorconfig handling.

**Comment by mvdan** [comment]
> So maybe it was fixed recently?

That sounds right - v3.5.0 swapped the default to `-ln=auto` to automatically detect languages based on filenames and shebangs. If you can update, that would be the best solution, as you're over a year out of date at this point. Debian has had v3.6.0 for some time, but I'm not sure how Ubuntu handles updates. You could always `go install` from source or download a binary from GitHub if you prefer to not use Docker.

> Anyway - I still believe that dialect options should not block editorconfig handling.

The latest release does the right thing for you here, so I'm inclined to not change documented behavior unless there's a good reason to do so, such as problems encountered in real codebases.

**Comment by scop** [comment]
An example real world problem caused by this is at https://github.com/radian-software/apheleia/pull/402

https://github.com/scop/bash-completion has a fairly specific .editorconfig for shfmt and other things. Apheleia used to pass `-ln` unconditionally based on which shell mode the editor is, as well as --indent= (conditionally) per how the editor is configured to indent. These settings in the editor may very well be based on the .editorconfig (done outside Apheleia, by another Emacs mode).

I agree that if one uses .editorconfig, then that should be the source of truth and other software should not ideally pass any options to shfmt to override it. But then again if there is no .editorconfig, I feel it's fine if the editor passes its own settings to shfmt for consistency. The editor might not have .editorconfig support though, and in my opinion requiring it to have it in order to decide whether to pass its options to shfmt or not, including knowing specifically which .editorconfig settings shfmt might use, is a big, possibly unsustainable ask.

For my particular use case, Apheleia no longer passing any options to shfmt solves the problem though.
