### ISSUE TITLE
syntax: exposing the lexer

### ISSUE THREAD

**Issue by hzlmn** [mvdan/sh#98]
Hi, do you plan to expose Lexer ? I need to operate on lower structures like tokens for some task. Can it be accomplished?

**Comment by mvdan** [comment]
I don't think that would be a good idea - the syntax package's exported API is large enough.

My other main concern is that the lexer has quite a few internal details and keeping it all internal means I can change things anytime without worrying about backwards compatibility.

**Comment by hzlmn** [comment]
Okay, I looked into code and notices that with current architecture it could be tricky so just was wondering do you plan to do. If so i will use custom processor for my task. Thanks.

**Comment by mvdan** [comment]
The architecture is designed for the parser in the same package, so it's likely that you would have difficulties re-using it. Even worse, due to the nature of the shell language, the line between the lexer and the parser is sometimes blurry. For example, `))` is not a token in the lexer but the parser emulates it - if it sees two `)` tokens right next to each other and it's not closing any parentheses.

You could also fork the lexer, if that could be useful.
