### ISSUE TITLE
shfmt bug: `&>` is broken onto a new line, while `>&` isn't

### ISSUE THREAD

**Issue by tandy-1000** [mvdan/sh#991]
When shfmt sees a `&>`, it is broken onto a new line:
```
{ echo "foo" } &>/dev/null || {
    echo "bar"
}
```

Becomes:
```
{ echo "foo" } &
	>/dev/null || {
    echo "bar"
}
```

The transformation also breaks the code.

If you switch `&>` with `>&` this does not happen.

**Comment by mvdan** [comment]
What did you run? Please fill the bug template. It's likely that you're trying to use POSIX mode when `&>` is bash syntax. Unfortunately, `&>` is also valid POSIX syntax; it just parses as `& >`, i.e. "background command then start a redirection".

**Comment by netrixken** [comment]
Just noticed today

`if ping -c 1 $default_gateway_ip &>/dev/null; then`

becomes

```
	if
		ping -c 1 $default_gateway_ip &
		>/dev/null
	then
```

Using https://marketplace.visualstudio.com/items?itemName=mkhl.shfmt

**Comment by mvdan** [comment]
The "fix" above is to give a helpful error, since I suspect that both of you were using POSIX mode to try to parse Bash syntax. You should be using the Bash mode, which should kick in automatically if your shell script has a `.bash` extension or a shebang like `#!/usr/bin/bash`. More details in the commit above.
