### ISSUE TITLE
"}" can only be used to close a block

### ISSUE THREAD

**Issue by leetrout** [mvdan/sh#993]
Given this code:

```bash
function help_msg {
	echo "Wrong arguments" >&2
	echo "Usage:"
	echo "  $0 -s source -d destination"
	echo "Options:"
	echo "  -s  Source vault"
	echo "  -d  Destination vault"
}
```

I am getting this error:

```
file.sh:10:1: "}" can only be used to close a block
```

I am unsure how to fix this

**Comment by mvdan** [comment]
What did you run? Please fill the bug template. It's likely that you're trying to parse in POSIX mode when this is bash syntax.

**Comment by leetrout** [comment]
I just ran `shfmt <file>`

Will respond with additional details on Monday when I am back at work but I did figure out to change it to not use the `function` keyword yesterday and it worked.

I am inheriting some shell scripts I didn't write - thank you for the hint to look at the mode.

**Comment by rgowtham** [comment]
I am seeing a similar behavior with the below function as well, 

```sh
function prettyTime {
    local _dt=$1
    local _dm
    local _dh
    local _ds
    _dh=$((_dt / 3600))
    _dm=$(((_dt / 60) % 60))
    _ds=$((_dt % 60))
    printf '%d:%02d:%02d' ${_dh} ${_dm} ${_ds}
}
```
```sh
~ shfmt run.sh
run.sh:41:1: "}" can only be used to close a block
```
I am using shfmt 3.7.0, not sure why shfmt considers this a bug

**Comment by mvdan** [comment]
@rgowtham as I tried to explain in my previous comment, this is not a bug in shfmt - the parser will work if you properly parse the script as Bash. You can do that explicitly via the `-ln=bash` flag, or by naming the script `foo.bash`, or by adding a shebang like `#!/usr/bin/bash`. Instead of any of those three options, your script probably just has a name like `foo.sh`, so the parser assumes POSIX shell, where `function` is not a valid way to declare functions.

**Comment by mvdan** [comment]
The parser should now give a better error message.
